// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: tag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagName       string                 `protobuf:"bytes,1,opt,name=tagName,proto3" json:"tagName,omitempty"` // 标签名
	TagDesc       string                 `protobuf:"bytes,2,opt,name=tagDesc,proto3" json:"tagDesc,omitempty"` // 标签描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTagRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *CreateTagRequest) GetTagDesc() string {
	if x != nil {
		return x.TagDesc
	}
	return ""
}

type CreateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"` // 标签ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	mi := &file_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagResponse) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`    // 标签ID
	TagName       string                 `protobuf:"bytes,2,opt,name=tagName,proto3" json:"tagName,omitempty"` // 标签名
	TagDesc       string                 `protobuf:"bytes,3,opt,name=tagDesc,proto3" json:"tagDesc,omitempty"` // 标签描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *UpdateTagRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *UpdateTagRequest) GetTagDesc() string {
	if x != nil {
		return x.TagDesc
	}
	return ""
}

type UpdateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResponse) Reset() {
	*x = UpdateTagResponse{}
	mi := &file_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResponse) ProtoMessage() {}

func (x *UpdateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{3}
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"` // 标签ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{5}
}

type TagDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"` // 标签ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDetailRequest) Reset() {
	*x = TagDetailRequest{}
	mi := &file_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDetailRequest) ProtoMessage() {}

func (x *TagDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDetailRequest.ProtoReflect.Descriptor instead.
func (*TagDetailRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{6}
}

func (x *TagDetailRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type TagDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`                 // 标签ID
	TagName       string                 `protobuf:"bytes,2,opt,name=tagName,proto3" json:"tagName,omitempty"`              // 标签名
	TagDesc       string                 `protobuf:"bytes,3,opt,name=tagDesc,proto3" json:"tagDesc,omitempty"`              // 标签描述
	ResourceCount int64                  `protobuf:"varint,4,opt,name=resourceCount,proto3" json:"resourceCount,omitempty"` // 关联资源数
	CreateTime    int64                  `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`       // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDetailResponse) Reset() {
	*x = TagDetailResponse{}
	mi := &file_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDetailResponse) ProtoMessage() {}

func (x *TagDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDetailResponse.ProtoReflect.Descriptor instead.
func (*TagDetailResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{7}
}

func (x *TagDetailResponse) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *TagDetailResponse) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *TagDetailResponse) GetTagDesc() string {
	if x != nil {
		return x.TagDesc
	}
	return ""
}

func (x *TagDetailResponse) GetResourceCount() int64 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *TagDetailResponse) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type TagListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`     // 游标
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListRequest) Reset() {
	*x = TagListRequest{}
	mi := &file_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListRequest) ProtoMessage() {}

func (x *TagListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListRequest.ProtoReflect.Descriptor instead.
func (*TagListRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{8}
}

func (x *TagListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *TagListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TagItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`                 // 标签ID
	TagName       string                 `protobuf:"bytes,2,opt,name=tagName,proto3" json:"tagName,omitempty"`              // 标签名
	TagDesc       string                 `protobuf:"bytes,3,opt,name=tagDesc,proto3" json:"tagDesc,omitempty"`              // 标签描述
	ResourceCount int64                  `protobuf:"varint,4,opt,name=resourceCount,proto3" json:"resourceCount,omitempty"` // 关联资源数
	CreateTime    int64                  `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`       // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagItem) Reset() {
	*x = TagItem{}
	mi := &file_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagItem) ProtoMessage() {}

func (x *TagItem) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagItem.ProtoReflect.Descriptor instead.
func (*TagItem) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{9}
}

func (x *TagItem) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *TagItem) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *TagItem) GetTagDesc() string {
	if x != nil {
		return x.TagDesc
	}
	return ""
}

func (x *TagItem) GetResourceCount() int64 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *TagItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type TagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TagItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`    // 标签列表
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // 下一页游标
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`   // 是否最后一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	mi := &file_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{10}
}

func (x *TagListResponse) GetItems() []*TagItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TagListResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *TagListResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type HotTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 数量上限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotTagsRequest) Reset() {
	*x = HotTagsRequest{}
	mi := &file_tag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotTagsRequest) ProtoMessage() {}

func (x *HotTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotTagsRequest.ProtoReflect.Descriptor instead.
func (*HotTagsRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{11}
}

func (x *HotTagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HotTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TagItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 热门标签列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotTagsResponse) Reset() {
	*x = HotTagsResponse{}
	mi := &file_tag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotTagsResponse) ProtoMessage() {}

func (x *HotTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotTagsResponse.ProtoReflect.Descriptor instead.
func (*HotTagsResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{12}
}

func (x *HotTagsResponse) GetItems() []*TagItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TagResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`        // 业务ID (如 "article" / "qa")
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"` // 资源ID
	TagId         int64                  `protobuf:"varint,3,opt,name=tagId,proto3" json:"tagId,omitempty"`       // 标签ID
	UserId        int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`     // 操作用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResourceRequest) Reset() {
	*x = TagResourceRequest{}
	mi := &file_tag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResourceRequest) ProtoMessage() {}

func (x *TagResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResourceRequest.ProtoReflect.Descriptor instead.
func (*TagResourceRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{13}
}

func (x *TagResourceRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *TagResourceRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *TagResourceRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *TagResourceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TagResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResourceResponse) Reset() {
	*x = TagResourceResponse{}
	mi := &file_tag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResourceResponse) ProtoMessage() {}

func (x *TagResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResourceResponse.ProtoReflect.Descriptor instead.
func (*TagResourceResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{14}
}

type UntagResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`        // 业务ID
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"` // 资源ID
	TagId         int64                  `protobuf:"varint,3,opt,name=tagId,proto3" json:"tagId,omitempty"`       // 标签ID
	UserId        int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`     // 操作用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntagResourceRequest) Reset() {
	*x = UntagResourceRequest{}
	mi := &file_tag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntagResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntagResourceRequest) ProtoMessage() {}

func (x *UntagResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntagResourceRequest.ProtoReflect.Descriptor instead.
func (*UntagResourceRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{15}
}

func (x *UntagResourceRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *UntagResourceRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *UntagResourceRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *UntagResourceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UntagResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntagResourceResponse) Reset() {
	*x = UntagResourceResponse{}
	mi := &file_tag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntagResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntagResourceResponse) ProtoMessage() {}

func (x *UntagResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntagResourceResponse.ProtoReflect.Descriptor instead.
func (*UntagResourceResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{16}
}

type ResourcesByTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`       // 标签ID
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`        // 业务ID (为空则查询所有业务)
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`     // 游标
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesByTagRequest) Reset() {
	*x = ResourcesByTagRequest{}
	mi := &file_tag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesByTagRequest) ProtoMessage() {}

func (x *ResourcesByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesByTagRequest.ProtoReflect.Descriptor instead.
func (*ResourcesByTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{17}
}

func (x *ResourcesByTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *ResourcesByTagRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ResourcesByTagRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ResourcesByTagRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ResourceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=targetId,proto3" json:"targetId,omitempty"`     // 资源ID
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`            // 业务ID
	CreateTime    int64                  `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"` // 打标签时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceItem) Reset() {
	*x = ResourceItem{}
	mi := &file_tag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceItem) ProtoMessage() {}

func (x *ResourceItem) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceItem.ProtoReflect.Descriptor instead.
func (*ResourceItem) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{18}
}

func (x *ResourceItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ResourceItem) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ResourceItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ResourcesByTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ResourceItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`    // 资源列表
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // 下一页游标
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`   // 是否最后一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesByTagResponse) Reset() {
	*x = ResourcesByTagResponse{}
	mi := &file_tag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesByTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesByTagResponse) ProtoMessage() {}

func (x *ResourcesByTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesByTagResponse.ProtoReflect.Descriptor instead.
func (*ResourcesByTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{19}
}

func (x *ResourcesByTagResponse) GetItems() []*ResourceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ResourcesByTagResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ResourcesByTagResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type TagsByResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`        // 业务ID
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"` // 资源ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsByResourceRequest) Reset() {
	*x = TagsByResourceRequest{}
	mi := &file_tag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsByResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsByResourceRequest) ProtoMessage() {}

func (x *TagsByResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsByResourceRequest.ProtoReflect.Descriptor instead.
func (*TagsByResourceRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{20}
}

func (x *TagsByResourceRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *TagsByResourceRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type TagsByResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TagItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 标签列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsByResourceResponse) Reset() {
	*x = TagsByResourceResponse{}
	mi := &file_tag_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsByResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsByResourceResponse) ProtoMessage() {}

func (x *TagsByResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsByResourceResponse.ProtoReflect.Descriptor instead.
func (*TagsByResourceResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{21}
}

func (x *TagsByResourceResponse) GetItems() []*TagItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_tag_proto protoreflect.FileDescriptor

const file_tag_proto_rawDesc = "" +
	"\n" +
	"\ttag.proto\x12\aservice\"F\n" +
	"\x10CreateTagRequest\x12\x18\n" +
	"\atagName\x18\x01 \x01(\tR\atagName\x12\x18\n" +
	"\atagDesc\x18\x02 \x01(\tR\atagDesc\")\n" +
	"\x11CreateTagResponse\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\"\\\n" +
	"\x10UpdateTagRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12\x18\n" +
	"\atagName\x18\x02 \x01(\tR\atagName\x12\x18\n" +
	"\atagDesc\x18\x03 \x01(\tR\atagDesc\"\x13\n" +
	"\x11UpdateTagResponse\"(\n" +
	"\x10DeleteTagRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\"\x13\n" +
	"\x11DeleteTagResponse\"(\n" +
	"\x10TagDetailRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\"\xa3\x01\n" +
	"\x11TagDetailResponse\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12\x18\n" +
	"\atagName\x18\x02 \x01(\tR\atagName\x12\x18\n" +
	"\atagDesc\x18\x03 \x01(\tR\atagDesc\x12$\n" +
	"\rresourceCount\x18\x04 \x01(\x03R\rresourceCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03R\n" +
	"createTime\"D\n" +
	"\x0eTagListRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"\x99\x01\n" +
	"\aTagItem\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12\x18\n" +
	"\atagName\x18\x02 \x01(\tR\atagName\x12\x18\n" +
	"\atagDesc\x18\x03 \x01(\tR\atagDesc\x12$\n" +
	"\rresourceCount\x18\x04 \x01(\x03R\rresourceCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03R\n" +
	"createTime\"g\n" +
	"\x0fTagListResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.service.TagItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"&\n" +
	"\x0eHotTagsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"9\n" +
	"\x0fHotTagsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.service.TagItemR\x05items\"t\n" +
	"\x12TagResourceRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\x12\x14\n" +
	"\x05tagId\x18\x03 \x01(\x03R\x05tagId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\"\x15\n" +
	"\x13TagResourceResponse\"v\n" +
	"\x14UntagResourceRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\x12\x14\n" +
	"\x05tagId\x18\x03 \x01(\x03R\x05tagId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\"\x17\n" +
	"\x15UntagResourceResponse\"w\n" +
	"\x15ResourcesByTagRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"`\n" +
	"\fResourceItem\x12\x1a\n" +
	"\btargetId\x18\x01 \x01(\x03R\btargetId\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x03 \x01(\x03R\n" +
	"createTime\"s\n" +
	"\x16ResourcesByTagResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.service.ResourceItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"I\n" +
	"\x15TagsByResourceRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\"@\n" +
	"\x16TagsByResourceResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.service.TagItemR\x05items2\xd1\x05\n" +
	"\x03Tag\x12B\n" +
	"\tCreateTag\x12\x19.service.CreateTagRequest\x1a\x1a.service.CreateTagResponse\x12B\n" +
	"\tUpdateTag\x12\x19.service.UpdateTagRequest\x1a\x1a.service.UpdateTagResponse\x12B\n" +
	"\tDeleteTag\x12\x19.service.DeleteTagRequest\x1a\x1a.service.DeleteTagResponse\x12B\n" +
	"\tTagDetail\x12\x19.service.TagDetailRequest\x1a\x1a.service.TagDetailResponse\x12<\n" +
	"\aTagList\x12\x17.service.TagListRequest\x1a\x18.service.TagListResponse\x12<\n" +
	"\aHotTags\x12\x17.service.HotTagsRequest\x1a\x18.service.HotTagsResponse\x12H\n" +
	"\vTagResource\x12\x1b.service.TagResourceRequest\x1a\x1c.service.TagResourceResponse\x12N\n" +
	"\rUntagResource\x12\x1d.service.UntagResourceRequest\x1a\x1e.service.UntagResourceResponse\x12Q\n" +
	"\x0eResourcesByTag\x12\x1e.service.ResourcesByTagRequest\x1a\x1f.service.ResourcesByTagResponse\x12Q\n" +
	"\x0eTagsByResource\x12\x1e.service.TagsByResourceRequest\x1a\x1f.service.TagsByResourceResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData []byte
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)))
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_tag_proto_goTypes = []any{
	(*CreateTagRequest)(nil),       // 0: service.CreateTagRequest
	(*CreateTagResponse)(nil),      // 1: service.CreateTagResponse
	(*UpdateTagRequest)(nil),       // 2: service.UpdateTagRequest
	(*UpdateTagResponse)(nil),      // 3: service.UpdateTagResponse
	(*DeleteTagRequest)(nil),       // 4: service.DeleteTagRequest
	(*DeleteTagResponse)(nil),      // 5: service.DeleteTagResponse
	(*TagDetailRequest)(nil),       // 6: service.TagDetailRequest
	(*TagDetailResponse)(nil),      // 7: service.TagDetailResponse
	(*TagListRequest)(nil),         // 8: service.TagListRequest
	(*TagItem)(nil),                // 9: service.TagItem
	(*TagListResponse)(nil),        // 10: service.TagListResponse
	(*HotTagsRequest)(nil),         // 11: service.HotTagsRequest
	(*HotTagsResponse)(nil),        // 12: service.HotTagsResponse
	(*TagResourceRequest)(nil),     // 13: service.TagResourceRequest
	(*TagResourceResponse)(nil),    // 14: service.TagResourceResponse
	(*UntagResourceRequest)(nil),   // 15: service.UntagResourceRequest
	(*UntagResourceResponse)(nil),  // 16: service.UntagResourceResponse
	(*ResourcesByTagRequest)(nil),  // 17: service.ResourcesByTagRequest
	(*ResourceItem)(nil),           // 18: service.ResourceItem
	(*ResourcesByTagResponse)(nil), // 19: service.ResourcesByTagResponse
	(*TagsByResourceRequest)(nil),  // 20: service.TagsByResourceRequest
	(*TagsByResourceResponse)(nil), // 21: service.TagsByResourceResponse
}
var file_tag_proto_depIdxs = []int32{
	9,  // 0: service.TagListResponse.items:type_name -> service.TagItem
	9,  // 1: service.HotTagsResponse.items:type_name -> service.TagItem
	18, // 2: service.ResourcesByTagResponse.items:type_name -> service.ResourceItem
	9,  // 3: service.TagsByResourceResponse.items:type_name -> service.TagItem
	0,  // 4: service.Tag.CreateTag:input_type -> service.CreateTagRequest
	2,  // 5: service.Tag.UpdateTag:input_type -> service.UpdateTagRequest
	4,  // 6: service.Tag.DeleteTag:input_type -> service.DeleteTagRequest
	6,  // 7: service.Tag.TagDetail:input_type -> service.TagDetailRequest
	8,  // 8: service.Tag.TagList:input_type -> service.TagListRequest
	11, // 9: service.Tag.HotTags:input_type -> service.HotTagsRequest
	13, // 10: service.Tag.TagResource:input_type -> service.TagResourceRequest
	15, // 11: service.Tag.UntagResource:input_type -> service.UntagResourceRequest
	17, // 12: service.Tag.ResourcesByTag:input_type -> service.ResourcesByTagRequest
	20, // 13: service.Tag.TagsByResource:input_type -> service.TagsByResourceRequest
	1,  // 14: service.Tag.CreateTag:output_type -> service.CreateTagResponse
	3,  // 15: service.Tag.UpdateTag:output_type -> service.UpdateTagResponse
	5,  // 16: service.Tag.DeleteTag:output_type -> service.DeleteTagResponse
	7,  // 17: service.Tag.TagDetail:output_type -> service.TagDetailResponse
	10, // 18: service.Tag.TagList:output_type -> service.TagListResponse
	12, // 19: service.Tag.HotTags:output_type -> service.HotTagsResponse
	14, // 20: service.Tag.TagResource:output_type -> service.TagResourceResponse
	16, // 21: service.Tag.UntagResource:output_type -> service.UntagResourceResponse
	19, // 22: service.Tag.ResourcesByTag:output_type -> service.ResourcesByTagResponse
	21, // 23: service.Tag.TagsByResource:output_type -> service.TagsByResourceResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
