// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: tag.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tag_CreateTag_FullMethodName      = "/service.Tag/CreateTag"
	Tag_UpdateTag_FullMethodName      = "/service.Tag/UpdateTag"
	Tag_DeleteTag_FullMethodName      = "/service.Tag/DeleteTag"
	Tag_TagDetail_FullMethodName      = "/service.Tag/TagDetail"
	Tag_TagList_FullMethodName        = "/service.Tag/TagList"
	Tag_HotTags_FullMethodName        = "/service.Tag/HotTags"
	Tag_TagResource_FullMethodName    = "/service.Tag/TagResource"
	Tag_UntagResource_FullMethodName  = "/service.Tag/UntagResource"
	Tag_ResourcesByTag_FullMethodName = "/service.Tag/ResourcesByTag"
	Tag_TagsByResource_FullMethodName = "/service.Tag/TagsByResource"
)

// TagClient is the client API for Tag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TagClient interface {
	// 创建标签
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	// 更新标签
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
	// 删除标签
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	// 标签详情
	TagDetail(ctx context.Context, in *TagDetailRequest, opts ...grpc.CallOption) (*TagDetailResponse, error)
	// 标签列表
	TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error)
	// 热门标签
	HotTags(ctx context.Context, in *HotTagsRequest, opts ...grpc.CallOption) (*HotTagsResponse, error)
	// 资源打标签
	TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*TagResourceResponse, error)
	// 资源去标签
	UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*UntagResourceResponse, error)
	// 标签下的资源列表
	ResourcesByTag(ctx context.Context, in *ResourcesByTagRequest, opts ...grpc.CallOption) (*ResourcesByTagResponse, error)
	// 资源关联的标签列表
	TagsByResource(ctx context.Context, in *TagsByResourceRequest, opts ...grpc.CallOption) (*TagsByResourceResponse, error)
}

type tagClient struct {
	cc grpc.ClientConnInterface
}

func NewTagClient(cc grpc.ClientConnInterface) TagClient {
	return &tagClient{cc}
}

func (c *tagClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, Tag_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTagResponse)
	err := c.cc.Invoke(ctx, Tag_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, Tag_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagDetail(ctx context.Context, in *TagDetailRequest, opts ...grpc.CallOption) (*TagDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagDetailResponse)
	err := c.cc.Invoke(ctx, Tag_TagDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagListResponse)
	err := c.cc.Invoke(ctx, Tag_TagList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) HotTags(ctx context.Context, in *HotTagsRequest, opts ...grpc.CallOption) (*HotTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotTagsResponse)
	err := c.cc.Invoke(ctx, Tag_HotTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*TagResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResourceResponse)
	err := c.cc.Invoke(ctx, Tag_TagResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*UntagResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UntagResourceResponse)
	err := c.cc.Invoke(ctx, Tag_UntagResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) ResourcesByTag(ctx context.Context, in *ResourcesByTagRequest, opts ...grpc.CallOption) (*ResourcesByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesByTagResponse)
	err := c.cc.Invoke(ctx, Tag_ResourcesByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagsByResource(ctx context.Context, in *TagsByResourceRequest, opts ...grpc.CallOption) (*TagsByResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagsByResourceResponse)
	err := c.cc.Invoke(ctx, Tag_TagsByResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServer is the server API for Tag service.
// All implementations must embed UnimplementedTagServer
// for forward compatibility.
type TagServer interface {
	// 创建标签
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	// 更新标签
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
	// 删除标签
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	// 标签详情
	TagDetail(context.Context, *TagDetailRequest) (*TagDetailResponse, error)
	// 标签列表
	TagList(context.Context, *TagListRequest) (*TagListResponse, error)
	// 热门标签
	HotTags(context.Context, *HotTagsRequest) (*HotTagsResponse, error)
	// 资源打标签
	TagResource(context.Context, *TagResourceRequest) (*TagResourceResponse, error)
	// 资源去标签
	UntagResource(context.Context, *UntagResourceRequest) (*UntagResourceResponse, error)
	// 标签下的资源列表
	ResourcesByTag(context.Context, *ResourcesByTagRequest) (*ResourcesByTagResponse, error)
	// 资源关联的标签列表
	TagsByResource(context.Context, *TagsByResourceRequest) (*TagsByResourceResponse, error)
	mustEmbedUnimplementedTagServer()
}

// UnimplementedTagServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTagServer struct{}

func (UnimplementedTagServer) CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedTagServer) UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedTagServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedTagServer) TagDetail(context.Context, *TagDetailRequest) (*TagDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagDetail not implemented")
}
func (UnimplementedTagServer) TagList(context.Context, *TagListRequest) (*TagListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagList not implemented")
}
func (UnimplementedTagServer) HotTags(context.Context, *HotTagsRequest) (*HotTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HotTags not implemented")
}
func (UnimplementedTagServer) TagResource(context.Context, *TagResourceRequest) (*TagResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagResource not implemented")
}
func (UnimplementedTagServer) UntagResource(context.Context, *UntagResourceRequest) (*UntagResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UntagResource not implemented")
}
func (UnimplementedTagServer) ResourcesByTag(context.Context, *ResourcesByTagRequest) (*ResourcesByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourcesByTag not implemented")
}
func (UnimplementedTagServer) TagsByResource(context.Context, *TagsByResourceRequest) (*TagsByResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagsByResource not implemented")
}
func (UnimplementedTagServer) mustEmbedUnimplementedTagServer() {}
func (UnimplementedTagServer) testEmbeddedByValue()             {}

// UnsafeTagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagServer will
// result in compilation errors.
type UnsafeTagServer interface {
	mustEmbedUnimplementedTagServer()
}

func RegisterTagServer(s grpc.ServiceRegistrar, srv TagServer) {
	// If the following call panics, it indicates UnimplementedTagServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tag_ServiceDesc, srv)
}

func _Tag_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagDetail(ctx, req.(*TagDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagList(ctx, req.(*TagListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_HotTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).HotTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_HotTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).HotTags(ctx, req.(*HotTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagResource(ctx, req.(*TagResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_UntagResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntagResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).UntagResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_UntagResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).UntagResource(ctx, req.(*UntagResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_ResourcesByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).ResourcesByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_ResourcesByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).ResourcesByTag(ctx, req.(*ResourcesByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagsByResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagsByResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagsByResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagsByResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagsByResource(ctx, req.(*TagsByResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tag_ServiceDesc is the grpc.ServiceDesc for Tag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Tag",
	HandlerType: (*TagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTag",
			Handler:    _Tag_CreateTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _Tag_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Tag_DeleteTag_Handler,
		},
		{
			MethodName: "TagDetail",
			Handler:    _Tag_TagDetail_Handler,
		},
		{
			MethodName: "TagList",
			Handler:    _Tag_TagList_Handler,
		},
		{
			MethodName: "HotTags",
			Handler:    _Tag_HotTags_Handler,
		},
		{
			MethodName: "TagResource",
			Handler:    _Tag_TagResource_Handler,
		},
		{
			MethodName: "UntagResource",
			Handler:    _Tag_UntagResource_Handler,
		},
		{
			MethodName: "ResourcesByTag",
			Handler:    _Tag_ResourcesByTag_Handler,
		},
		{
			MethodName: "TagsByResource",
			Handler:    _Tag_TagsByResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tag.proto",
}
