// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`     // 用户ID
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`     // 游标
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 页大小
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`         // 通知类型 (0表示全部)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationListRequest) Reset() {
	*x = NotificationListRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationListRequest) ProtoMessage() {}

func (x *NotificationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationListRequest.ProtoReflect.Descriptor instead.
func (*NotificationListRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *NotificationListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *NotificationListRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type NotificationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                       // 通知ID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                   // 通知类型
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                  // 通知标题
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`              // 通知内容
	RefId         int64                  `protobuf:"varint,5,opt,name=refId,proto3" json:"refId,omitempty"`                 // 关联资源ID
	BizId         string                 `protobuf:"bytes,6,opt,name=bizId,proto3" json:"bizId,omitempty"`                  // 业务ID
	TriggerUserId int64                  `protobuf:"varint,7,opt,name=triggerUserId,proto3" json:"triggerUserId,omitempty"` // 触发用户ID
	IsRead        bool                   `protobuf:"varint,8,opt,name=isRead,proto3" json:"isRead,omitempty"`               // 是否已读
	CreateTime    int64                  `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`       // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NotificationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationItem) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *NotificationItem) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *NotificationItem) GetTriggerUserId() int64 {
	if x != nil {
		return x.TriggerUserId
	}
	return 0
}

func (x *NotificationItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type NotificationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NotificationItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`    // 通知列表
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // 下一页游标
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`   // 是否最后一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationListResponse) Reset() {
	*x = NotificationListResponse{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationListResponse) ProtoMessage() {}

func (x *NotificationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationListResponse.ProtoReflect.Descriptor instead.
func (*NotificationListResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationListResponse) GetItems() []*NotificationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *NotificationListResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *NotificationListResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type UnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountRequest) Reset() {
	*x = UnreadCountRequest{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountRequest) ProtoMessage() {}

func (x *UnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountRequest.ProtoReflect.Descriptor instead.
func (*UnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *UnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                                                                      // 总未读数
	TypeCounts    map[int32]int64        `protobuf:"bytes,2,rep,name=typeCounts,proto3" json:"typeCounts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 各类型未读数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountResponse) Reset() {
	*x = UnreadCountResponse{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountResponse) ProtoMessage() {}

func (x *UnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountResponse.ProtoReflect.Descriptor instead.
func (*UnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *UnreadCountResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UnreadCountResponse) GetTypeCounts() map[int32]int64 {
	if x != nil {
		return x.TypeCounts
	}
	return nil
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`                 // 用户ID
	NotificationId int64                  `protobuf:"varint,2,opt,name=notificationId,proto3" json:"notificationId,omitempty"` // 通知ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *MarkReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkReadRequest) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

type MarkAllReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`     // 通知类型 (0表示全部类型)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadRequest) Reset() {
	*x = MarkAllReadRequest{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadRequest) ProtoMessage() {}

func (x *MarkAllReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllReadRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAllReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkAllReadRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type MarkAllReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadResponse) Reset() {
	*x = MarkAllReadResponse{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadResponse) ProtoMessage() {}

func (x *MarkAllReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllReadResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\aservice\"y\n" +
	"\x17NotificationListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\"\xf0\x01\n" +
	"\x10NotificationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05refId\x18\x05 \x01(\x03R\x05refId\x12\x14\n" +
	"\x05bizId\x18\x06 \x01(\tR\x05bizId\x12$\n" +
	"\rtriggerUserId\x18\a \x01(\x03R\rtriggerUserId\x12\x16\n" +
	"\x06isRead\x18\b \x01(\bR\x06isRead\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\x03R\n" +
	"createTime\"y\n" +
	"\x18NotificationListResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.service.NotificationItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\",\n" +
	"\x12UnreadCountRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\xb8\x01\n" +
	"\x13UnreadCountResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12L\n" +
	"\n" +
	"typeCounts\x18\x02 \x03(\v2,.service.UnreadCountResponse.TypeCountsEntryR\n" +
	"typeCounts\x1a=\n" +
	"\x0fTypeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"Q\n" +
	"\x0fMarkReadRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0enotificationId\x18\x02 \x01(\x03R\x0enotificationId\"\x12\n" +
	"\x10MarkReadResponse\"@\n" +
	"\x12MarkAllReadRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"\x15\n" +
	"\x13MarkAllReadResponse2\xb7\x02\n" +
	"\aMessage\x12W\n" +
	"\x10NotificationList\x12 .service.NotificationListRequest\x1a!.service.NotificationListResponse\x12H\n" +
	"\vUnreadCount\x12\x1b.service.UnreadCountRequest\x1a\x1c.service.UnreadCountResponse\x12?\n" +
	"\bMarkRead\x12\x18.service.MarkReadRequest\x1a\x19.service.MarkReadResponse\x12H\n" +
	"\vMarkAllRead\x12\x1b.service.MarkAllReadRequest\x1a\x1c.service.MarkAllReadResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_message_proto_goTypes = []any{
	(*NotificationListRequest)(nil),  // 0: service.NotificationListRequest
	(*NotificationItem)(nil),         // 1: service.NotificationItem
	(*NotificationListResponse)(nil), // 2: service.NotificationListResponse
	(*UnreadCountRequest)(nil),       // 3: service.UnreadCountRequest
	(*UnreadCountResponse)(nil),      // 4: service.UnreadCountResponse
	(*MarkReadRequest)(nil),          // 5: service.MarkReadRequest
	(*MarkReadResponse)(nil),         // 6: service.MarkReadResponse
	(*MarkAllReadRequest)(nil),       // 7: service.MarkAllReadRequest
	(*MarkAllReadResponse)(nil),      // 8: service.MarkAllReadResponse
	nil,                              // 9: service.UnreadCountResponse.TypeCountsEntry
}
var file_message_proto_depIdxs = []int32{
	1, // 0: service.NotificationListResponse.items:type_name -> service.NotificationItem
	9, // 1: service.UnreadCountResponse.typeCounts:type_name -> service.UnreadCountResponse.TypeCountsEntry
	0, // 2: service.Message.NotificationList:input_type -> service.NotificationListRequest
	3, // 3: service.Message.UnreadCount:input_type -> service.UnreadCountRequest
	5, // 4: service.Message.MarkRead:input_type -> service.MarkReadRequest
	7, // 5: service.Message.MarkAllRead:input_type -> service.MarkAllReadRequest
	2, // 6: service.Message.NotificationList:output_type -> service.NotificationListResponse
	4, // 7: service.Message.UnreadCount:output_type -> service.UnreadCountResponse
	6, // 8: service.Message.MarkRead:output_type -> service.MarkReadResponse
	8, // 9: service.Message.MarkAllRead:output_type -> service.MarkAllReadResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
