// Code generated by goctl. DO NOT EDIT. (Manually modified to register all routes)
// goctl 1.10.1

package handler

import (
	"net/http"

	"ThinkTalk/application/applet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 1. 公开 / 基础用户路由 (Prefix: /v1)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verification",
				Handler: VerificationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	// 2. 用户基本信息路由组 (Prefix: /v1/user)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/user"),
	)

	// 3. 点赞路由组 (Prefix: /v1/like)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/thumbup",
				Handler: ThumbupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/thumbup",
				Handler: IsThumbupHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/like"),
	)

	// 4. 关注路由组 (Prefix: /v1/follow)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unfollow",
				Handler: UnFollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: FollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/fans",
				Handler: FansListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/follow"),
	)

	// 5. 收藏路由组 (Prefix: /v1/concerned)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: ConcernedAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cancel",
				Handler: ConcernedCancelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/check",
				Handler: ConcernedCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: ConcernedListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/count",
				Handler: ConcernedCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/concerned"),
	)

	// 6. 会员路由组 (Prefix: /v1/member)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: MemberInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/right",
				Handler: MemberRightHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upgrade",
				Handler: UpgradeMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: MemberOrderListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/member"),
	)

	// 7. 消息通知路由组 (Prefix: /v1/message)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: NotificationListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/unread",
				Handler: UnreadCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: MarkReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/readall",
				Handler: MarkAllReadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/message"),
	)

	// 8. 标签路由组 (Prefix: /v1/tag)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: TagCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: TagUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: TagDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: TagDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: TagListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/hot",
				Handler: HotTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resource/add",
				Handler: TagResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resource/remove",
				Handler: UntagResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resource/list",
				Handler: ResourcesByTagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resource/tags",
				Handler: TagsByResourceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/tag"),
	)

	// 9. 评论回复路由组 (Prefix: /v1/reply)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: ReplyCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: ReplyDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: ReplyDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: ReplyListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/count",
				Handler: ReplyCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/reply"),
	)
}
