// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: qa.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TagIds        string                 `protobuf:"bytes,4,opt,name=tagIds,proto3" json:"tagIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuestionRequest) Reset() {
	*x = PublishQuestionRequest{}
	mi := &file_qa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuestionRequest) ProtoMessage() {}

func (x *PublishQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuestionRequest.ProtoReflect.Descriptor instead.
func (*PublishQuestionRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{0}
}

func (x *PublishQuestionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishQuestionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublishQuestionRequest) GetTagIds() string {
	if x != nil {
		return x.TagIds
	}
	return ""
}

type PublishQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=questionId,proto3" json:"questionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuestionResponse) Reset() {
	*x = PublishQuestionResponse{}
	mi := &file_qa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuestionResponse) ProtoMessage() {}

func (x *PublishQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuestionResponse.ProtoReflect.Descriptor instead.
func (*PublishQuestionResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{1}
}

func (x *PublishQuestionResponse) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type AnswerQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=questionId,proto3" json:"questionId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionRequest) Reset() {
	*x = AnswerQuestionRequest{}
	mi := &file_qa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionRequest) ProtoMessage() {}

func (x *AnswerQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionRequest.ProtoReflect.Descriptor instead.
func (*AnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{2}
}

func (x *AnswerQuestionRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerQuestionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnswerQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AnswerQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerId      int64                  `protobuf:"varint,1,opt,name=answerId,proto3" json:"answerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionResponse) Reset() {
	*x = AnswerQuestionResponse{}
	mi := &file_qa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionResponse) ProtoMessage() {}

func (x *AnswerQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionResponse.ProtoReflect.Descriptor instead.
func (*AnswerQuestionResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{3}
}

func (x *AnswerQuestionResponse) GetAnswerId() int64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

type AcceptAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=questionId,proto3" json:"questionId,omitempty"`
	AnswerId      int64                  `protobuf:"varint,2,opt,name=answerId,proto3" json:"answerId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptAnswerRequest) Reset() {
	*x = AcceptAnswerRequest{}
	mi := &file_qa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptAnswerRequest) ProtoMessage() {}

func (x *AcceptAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptAnswerRequest.ProtoReflect.Descriptor instead.
func (*AcceptAnswerRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptAnswerRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AcceptAnswerRequest) GetAnswerId() int64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

func (x *AcceptAnswerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AcceptAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptAnswerResponse) Reset() {
	*x = AcceptAnswerResponse{}
	mi := &file_qa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptAnswerResponse) ProtoMessage() {}

func (x *AcceptAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptAnswerResponse.ProtoReflect.Descriptor instead.
func (*AcceptAnswerResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{5}
}

type QuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SortType      int32                  `protobuf:"varint,4,opt,name=sortType,proto3" json:"sortType,omitempty"` // 0:按时间 1:按热度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionsRequest) Reset() {
	*x = QuestionsRequest{}
	mi := &file_qa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionsRequest) ProtoMessage() {}

func (x *QuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionsRequest.ProtoReflect.Descriptor instead.
func (*QuestionsRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *QuestionsRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *QuestionsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QuestionsRequest) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

type QuestionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=authorId,proto3" json:"authorId,omitempty"`
	AnswerNum     int64                  `protobuf:"varint,5,opt,name=answerNum,proto3" json:"answerNum,omitempty"`
	ViewNum       int64                  `protobuf:"varint,6,opt,name=viewNum,proto3" json:"viewNum,omitempty"`
	TagIds        string                 `protobuf:"bytes,7,opt,name=tagIds,proto3" json:"tagIds,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionItem) Reset() {
	*x = QuestionItem{}
	mi := &file_qa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionItem) ProtoMessage() {}

func (x *QuestionItem) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionItem.ProtoReflect.Descriptor instead.
func (*QuestionItem) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QuestionItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *QuestionItem) GetAnswerNum() int64 {
	if x != nil {
		return x.AnswerNum
	}
	return 0
}

func (x *QuestionItem) GetViewNum() int64 {
	if x != nil {
		return x.ViewNum
	}
	return 0
}

func (x *QuestionItem) GetTagIds() string {
	if x != nil {
		return x.TagIds
	}
	return ""
}

func (x *QuestionItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type QuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QuestionItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	QuestionId    int64                  `protobuf:"varint,4,opt,name=questionId,proto3" json:"questionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionsResponse) Reset() {
	*x = QuestionsResponse{}
	mi := &file_qa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionsResponse) ProtoMessage() {}

func (x *QuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionsResponse.ProtoReflect.Descriptor instead.
func (*QuestionsResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{8}
}

func (x *QuestionsResponse) GetItems() []*QuestionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *QuestionsResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *QuestionsResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *QuestionsResponse) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type QuestionDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=questionId,proto3" json:"questionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionDetailRequest) Reset() {
	*x = QuestionDetailRequest{}
	mi := &file_qa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDetailRequest) ProtoMessage() {}

func (x *QuestionDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDetailRequest.ProtoReflect.Descriptor instead.
func (*QuestionDetailRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{9}
}

func (x *QuestionDetailRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type QuestionDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *QuestionItem          `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionDetailResponse) Reset() {
	*x = QuestionDetailResponse{}
	mi := &file_qa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDetailResponse) ProtoMessage() {}

func (x *QuestionDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDetailResponse.ProtoReflect.Descriptor instead.
func (*QuestionDetailResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{10}
}

func (x *QuestionDetailResponse) GetQuestion() *QuestionItem {
	if x != nil {
		return x.Question
	}
	return nil
}

type QuestionDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=questionId,proto3" json:"questionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionDeleteRequest) Reset() {
	*x = QuestionDeleteRequest{}
	mi := &file_qa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDeleteRequest) ProtoMessage() {}

func (x *QuestionDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDeleteRequest.ProtoReflect.Descriptor instead.
func (*QuestionDeleteRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{11}
}

func (x *QuestionDeleteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *QuestionDeleteRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type QuestionDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionDeleteResponse) Reset() {
	*x = QuestionDeleteResponse{}
	mi := &file_qa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDeleteResponse) ProtoMessage() {}

func (x *QuestionDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDeleteResponse.ProtoReflect.Descriptor instead.
func (*QuestionDeleteResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{12}
}

type AnswerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=questionId,proto3" json:"questionId,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerListRequest) Reset() {
	*x = AnswerListRequest{}
	mi := &file_qa_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerListRequest) ProtoMessage() {}

func (x *AnswerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerListRequest.ProtoReflect.Descriptor instead.
func (*AnswerListRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{13}
}

func (x *AnswerListRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *AnswerListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AnswerItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=questionId,proto3" json:"questionId,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsAccepted    bool                   `protobuf:"varint,5,opt,name=isAccepted,proto3" json:"isAccepted,omitempty"`
	LikeNum       int64                  `protobuf:"varint,6,opt,name=likeNum,proto3" json:"likeNum,omitempty"`
	ReplyNum      int64                  `protobuf:"varint,7,opt,name=replyNum,proto3" json:"replyNum,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerItem) Reset() {
	*x = AnswerItem{}
	mi := &file_qa_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerItem) ProtoMessage() {}

func (x *AnswerItem) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerItem.ProtoReflect.Descriptor instead.
func (*AnswerItem) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{14}
}

func (x *AnswerItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerItem) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *AnswerItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnswerItem) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *AnswerItem) GetLikeNum() int64 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *AnswerItem) GetReplyNum() int64 {
	if x != nil {
		return x.ReplyNum
	}
	return 0
}

func (x *AnswerItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type AnswerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnswerItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerListResponse) Reset() {
	*x = AnswerListResponse{}
	mi := &file_qa_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerListResponse) ProtoMessage() {}

func (x *AnswerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerListResponse.ProtoReflect.Descriptor instead.
func (*AnswerListResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{15}
}

func (x *AnswerListResponse) GetItems() []*AnswerItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AnswerListResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *AnswerListResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type AnswerDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AnswerId      int64                  `protobuf:"varint,2,opt,name=answerId,proto3" json:"answerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerDeleteRequest) Reset() {
	*x = AnswerDeleteRequest{}
	mi := &file_qa_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerDeleteRequest) ProtoMessage() {}

func (x *AnswerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerDeleteRequest.ProtoReflect.Descriptor instead.
func (*AnswerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{16}
}

func (x *AnswerDeleteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnswerDeleteRequest) GetAnswerId() int64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

type AnswerDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerDeleteResponse) Reset() {
	*x = AnswerDeleteResponse{}
	mi := &file_qa_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerDeleteResponse) ProtoMessage() {}

func (x *AnswerDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerDeleteResponse.ProtoReflect.Descriptor instead.
func (*AnswerDeleteResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{17}
}

type SearchQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsRequest) Reset() {
	*x = SearchQuestionsRequest{}
	mi := &file_qa_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsRequest) ProtoMessage() {}

func (x *SearchQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsRequest.ProtoReflect.Descriptor instead.
func (*SearchQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{18}
}

func (x *SearchQuestionsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchQuestionsRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SearchQuestionsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchQuestionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=authorId,proto3" json:"authorId,omitempty"`
	AnswerNum     int64                  `protobuf:"varint,5,opt,name=answerNum,proto3" json:"answerNum,omitempty"`
	TagIds        string                 `protobuf:"bytes,6,opt,name=tagIds,proto3" json:"tagIds,omitempty"`
	CreateTime    int64                  `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionItem) Reset() {
	*x = SearchQuestionItem{}
	mi := &file_qa_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionItem) ProtoMessage() {}

func (x *SearchQuestionItem) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionItem.ProtoReflect.Descriptor instead.
func (*SearchQuestionItem) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{19}
}

func (x *SearchQuestionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchQuestionItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchQuestionItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchQuestionItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SearchQuestionItem) GetAnswerNum() int64 {
	if x != nil {
		return x.AnswerNum
	}
	return 0
}

func (x *SearchQuestionItem) GetTagIds() string {
	if x != nil {
		return x.TagIds
	}
	return ""
}

func (x *SearchQuestionItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type SearchQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SearchQuestionItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsResponse) Reset() {
	*x = SearchQuestionsResponse{}
	mi := &file_qa_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsResponse) ProtoMessage() {}

func (x *SearchQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qa_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SearchQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_qa_proto_rawDescGZIP(), []int{20}
}

func (x *SearchQuestionsResponse) GetItems() []*SearchQuestionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchQuestionsResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SearchQuestionsResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

var File_qa_proto protoreflect.FileDescriptor

const file_qa_proto_rawDesc = "" +
	"\n" +
	"\bqa.proto\x12\aservice\"x\n" +
	"\x16PublishQuestionRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06tagIds\x18\x04 \x01(\tR\x06tagIds\"9\n" +
	"\x17PublishQuestionResponse\x12\x1e\n" +
	"\n" +
	"questionId\x18\x01 \x01(\x03R\n" +
	"questionId\"i\n" +
	"\x15AnswerQuestionRequest\x12\x1e\n" +
	"\n" +
	"questionId\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"4\n" +
	"\x16AnswerQuestionResponse\x12\x1a\n" +
	"\banswerId\x18\x01 \x01(\x03R\banswerId\"i\n" +
	"\x13AcceptAnswerRequest\x12\x1e\n" +
	"\n" +
	"questionId\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x1a\n" +
	"\banswerId\x18\x02 \x01(\x03R\banswerId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"\x16\n" +
	"\x14AcceptAnswerResponse\"z\n" +
	"\x10QuestionsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bsortType\x18\x04 \x01(\x05R\bsortType\"\xda\x01\n" +
	"\fQuestionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bauthorId\x18\x04 \x01(\x03R\bauthorId\x12\x1c\n" +
	"\tanswerNum\x18\x05 \x01(\x03R\tanswerNum\x12\x18\n" +
	"\aviewNum\x18\x06 \x01(\x03R\aviewNum\x12\x16\n" +
	"\x06tagIds\x18\a \x01(\tR\x06tagIds\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\"\x8e\x01\n" +
	"\x11QuestionsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.service.QuestionItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\x12\x1e\n" +
	"\n" +
	"questionId\x18\x04 \x01(\x03R\n" +
	"questionId\"7\n" +
	"\x15QuestionDetailRequest\x12\x1e\n" +
	"\n" +
	"questionId\x18\x01 \x01(\x03R\n" +
	"questionId\"K\n" +
	"\x16QuestionDetailResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.service.QuestionItemR\bquestion\"O\n" +
	"\x15QuestionDeleteRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"questionId\x18\x02 \x01(\x03R\n" +
	"questionId\"\x18\n" +
	"\x16QuestionDeleteResponse\"g\n" +
	"\x11AnswerListRequest\x12\x1e\n" +
	"\n" +
	"questionId\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\xe8\x01\n" +
	"\n" +
	"AnswerItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"questionId\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x1a\n" +
	"\bauthorId\x18\x03 \x01(\x03R\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"isAccepted\x18\x05 \x01(\bR\n" +
	"isAccepted\x12\x18\n" +
	"\alikeNum\x18\x06 \x01(\x03R\alikeNum\x12\x1a\n" +
	"\breplyNum\x18\a \x01(\x03R\breplyNum\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\"m\n" +
	"\x12AnswerListResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.service.AnswerItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"I\n" +
	"\x13AnswerDeleteRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\banswerId\x18\x02 \x01(\x03R\banswerId\"\x16\n" +
	"\x14AnswerDeleteResponse\"f\n" +
	"\x16SearchQuestionsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\xc6\x01\n" +
	"\x12SearchQuestionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bauthorId\x18\x04 \x01(\x03R\bauthorId\x12\x1c\n" +
	"\tanswerNum\x18\x05 \x01(\x03R\tanswerNum\x12\x16\n" +
	"\x06tagIds\x18\x06 \x01(\tR\x06tagIds\x12\x1e\n" +
	"\n" +
	"createTime\x18\a \x01(\x03R\n" +
	"createTime\"z\n" +
	"\x17SearchQuestionsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.service.SearchQuestionItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd2\xce\x05\n" +
	"\x02QA\x12T\n" +
	"\x0fPublishQuestion\x12\x1f.service.PublishQuestionRequest\x1a .service.PublishQuestionResponse\x12Q\n" +
	"\x0eAnswerQuestion\x12\x1e.service.AnswerQuestionRequest\x1a\x1f.service.AnswerQuestionResponse\x12K\n" +
	"\fAcceptAnswer\x12\x1c.service.AcceptAnswerRequest\x1a\x1d.service.AcceptAnswerResponse\x12B\n" +
	"\tQuestions\x12\x19.service.QuestionsRequest\x1a\x1a.service.QuestionsResponse\x12Q\n" +
	"\x0eQuestionDetail\x12\x1e.service.QuestionDetailRequest\x1a\x1f.service.QuestionDetailResponse\x12Q\n" +
	"\x0eQuestionDelete\x12\x1e.service.QuestionDeleteRequest\x1a\x1f.service.QuestionDeleteResponse\x12E\n" +
	"\n" +
	"AnswerList\x12\x1a.service.AnswerListRequest\x1a\x1b.service.AnswerListResponse\x12K\n" +
	"\fAnswerDelete\x12\x1c.service.AnswerDeleteRequest\x1a\x1d.service.AnswerDeleteResponse\x12T\n" +
	"\x0fSearchQuestions\x12\x1f.service.SearchQuestionsRequest\x1a .service.SearchQuestionsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_qa_proto_rawDescOnce sync.Once
	file_qa_proto_rawDescData []byte
)

func file_qa_proto_rawDescGZIP() []byte {
	file_qa_proto_rawDescOnce.Do(func() {
		file_qa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qa_proto_rawDesc), len(file_qa_proto_rawDesc)))
	})
	return file_qa_proto_rawDescData
}

var file_qa_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_qa_proto_goTypes = []any{
	(*PublishQuestionRequest)(nil),  // 0: service.PublishQuestionRequest
	(*PublishQuestionResponse)(nil), // 1: service.PublishQuestionResponse
	(*AnswerQuestionRequest)(nil),   // 2: service.AnswerQuestionRequest
	(*AnswerQuestionResponse)(nil),  // 3: service.AnswerQuestionResponse
	(*AcceptAnswerRequest)(nil),     // 4: service.AcceptAnswerRequest
	(*AcceptAnswerResponse)(nil),    // 5: service.AcceptAnswerResponse
	(*QuestionsRequest)(nil),        // 6: service.QuestionsRequest
	(*QuestionItem)(nil),            // 7: service.QuestionItem
	(*QuestionsResponse)(nil),       // 8: service.QuestionsResponse
	(*QuestionDetailRequest)(nil),   // 9: service.QuestionDetailRequest
	(*QuestionDetailResponse)(nil),  // 10: service.QuestionDetailResponse
	(*QuestionDeleteRequest)(nil),   // 11: service.QuestionDeleteRequest
	(*QuestionDeleteResponse)(nil),  // 12: service.QuestionDeleteResponse
	(*AnswerListRequest)(nil),       // 13: service.AnswerListRequest
	(*AnswerItem)(nil),              // 14: service.AnswerItem
	(*AnswerListResponse)(nil),      // 15: service.AnswerListResponse
	(*AnswerDeleteRequest)(nil),     // 16: service.AnswerDeleteRequest
	(*AnswerDeleteResponse)(nil),    // 17: service.AnswerDeleteResponse
	(*SearchQuestionsRequest)(nil),  // 18: service.SearchQuestionsRequest
	(*SearchQuestionItem)(nil),      // 19: service.SearchQuestionItem
	(*SearchQuestionsResponse)(nil), // 20: service.SearchQuestionsResponse
}
var file_qa_proto_depIdxs = []int32{
	7,  // 0: service.QuestionsResponse.items:type_name -> service.QuestionItem
	7,  // 1: service.QuestionDetailResponse.question:type_name -> service.QuestionItem
	14, // 2: service.AnswerListResponse.items:type_name -> service.AnswerItem
	19, // 3: service.SearchQuestionsResponse.items:type_name -> service.SearchQuestionItem
	0,  // 4: service.QA.PublishQuestion:input_type -> service.PublishQuestionRequest
	2,  // 5: service.QA.AnswerQuestion:input_type -> service.AnswerQuestionRequest
	4,  // 6: service.QA.AcceptAnswer:input_type -> service.AcceptAnswerRequest
	6,  // 7: service.QA.Questions:input_type -> service.QuestionsRequest
	9,  // 8: service.QA.QuestionDetail:input_type -> service.QuestionDetailRequest
	11, // 9: service.QA.QuestionDelete:input_type -> service.QuestionDeleteRequest
	13, // 10: service.QA.AnswerList:input_type -> service.AnswerListRequest
	16, // 11: service.QA.AnswerDelete:input_type -> service.AnswerDeleteRequest
	18, // 12: service.QA.SearchQuestions:input_type -> service.SearchQuestionsRequest
	1,  // 13: service.QA.PublishQuestion:output_type -> service.PublishQuestionResponse
	3,  // 14: service.QA.AnswerQuestion:output_type -> service.AnswerQuestionResponse
	5,  // 15: service.QA.AcceptAnswer:output_type -> service.AcceptAnswerResponse
	8,  // 16: service.QA.Questions:output_type -> service.QuestionsResponse
	10, // 17: service.QA.QuestionDetail:output_type -> service.QuestionDetailResponse
	12, // 18: service.QA.QuestionDelete:output_type -> service.QuestionDeleteResponse
	15, // 19: service.QA.AnswerList:output_type -> service.AnswerListResponse
	17, // 20: service.QA.AnswerDelete:output_type -> service.AnswerDeleteResponse
	20, // 21: service.QA.SearchQuestions:output_type -> service.SearchQuestionsResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_qa_proto_init() }
func file_qa_proto_init() {
	if File_qa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qa_proto_rawDesc), len(file_qa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qa_proto_goTypes,
		DependencyIndexes: file_qa_proto_depIdxs,
		MessageInfos:      file_qa_proto_msgTypes,
	}.Build()
	File_qa_proto = out.File
	file_qa_proto_goTypes = nil
	file_qa_proto_depIdxs = nil
}
