// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: qa.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QA_PublishQuestion_FullMethodName = "/service.QA/PublishQuestion"
	QA_AnswerQuestion_FullMethodName  = "/service.QA/AnswerQuestion"
	QA_AcceptAnswer_FullMethodName    = "/service.QA/AcceptAnswer"
	QA_Questions_FullMethodName       = "/service.QA/Questions"
	QA_QuestionDetail_FullMethodName  = "/service.QA/QuestionDetail"
	QA_QuestionDelete_FullMethodName  = "/service.QA/QuestionDelete"
	QA_AnswerList_FullMethodName      = "/service.QA/AnswerList"
	QA_AnswerDelete_FullMethodName    = "/service.QA/AnswerDelete"
	QA_SearchQuestions_FullMethodName = "/service.QA/SearchQuestions"
)

// QAClient is the client API for QA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QAClient interface {
	// 发布问题
	PublishQuestion(ctx context.Context, in *PublishQuestionRequest, opts ...grpc.CallOption) (*PublishQuestionResponse, error)
	// 回答
	AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (*AnswerQuestionResponse, error)
	// 采纳回答
	AcceptAnswer(ctx context.Context, in *AcceptAnswerRequest, opts ...grpc.CallOption) (*AcceptAnswerResponse, error)
	// 问题列表
	Questions(ctx context.Context, in *QuestionsRequest, opts ...grpc.CallOption) (*QuestionsResponse, error)
	// 问题详情
	QuestionDetail(ctx context.Context, in *QuestionDetailRequest, opts ...grpc.CallOption) (*QuestionDetailResponse, error)
	// 删除问题
	QuestionDelete(ctx context.Context, in *QuestionDeleteRequest, opts ...grpc.CallOption) (*QuestionDeleteResponse, error)
	// 回答列表
	AnswerList(ctx context.Context, in *AnswerListRequest, opts ...grpc.CallOption) (*AnswerListResponse, error)
	// 删除回答
	AnswerDelete(ctx context.Context, in *AnswerDeleteRequest, opts ...grpc.CallOption) (*AnswerDeleteResponse, error)
	// 搜索问题
	SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error)
}

type qAClient struct {
	cc grpc.ClientConnInterface
}

func NewQAClient(cc grpc.ClientConnInterface) QAClient {
	return &qAClient{cc}
}

func (c *qAClient) PublishQuestion(ctx context.Context, in *PublishQuestionRequest, opts ...grpc.CallOption) (*PublishQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishQuestionResponse)
	err := c.cc.Invoke(ctx, QA_PublishQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (*AnswerQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerQuestionResponse)
	err := c.cc.Invoke(ctx, QA_AnswerQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AcceptAnswer(ctx context.Context, in *AcceptAnswerRequest, opts ...grpc.CallOption) (*AcceptAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptAnswerResponse)
	err := c.cc.Invoke(ctx, QA_AcceptAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) Questions(ctx context.Context, in *QuestionsRequest, opts ...grpc.CallOption) (*QuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionsResponse)
	err := c.cc.Invoke(ctx, QA_Questions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) QuestionDetail(ctx context.Context, in *QuestionDetailRequest, opts ...grpc.CallOption) (*QuestionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionDetailResponse)
	err := c.cc.Invoke(ctx, QA_QuestionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) QuestionDelete(ctx context.Context, in *QuestionDeleteRequest, opts ...grpc.CallOption) (*QuestionDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionDeleteResponse)
	err := c.cc.Invoke(ctx, QA_QuestionDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AnswerList(ctx context.Context, in *AnswerListRequest, opts ...grpc.CallOption) (*AnswerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerListResponse)
	err := c.cc.Invoke(ctx, QA_AnswerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AnswerDelete(ctx context.Context, in *AnswerDeleteRequest, opts ...grpc.CallOption) (*AnswerDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerDeleteResponse)
	err := c.cc.Invoke(ctx, QA_AnswerDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchQuestionsResponse)
	err := c.cc.Invoke(ctx, QA_SearchQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QAServer is the server API for QA service.
// All implementations must embed UnimplementedQAServer
// for forward compatibility.
type QAServer interface {
	// 发布问题
	PublishQuestion(context.Context, *PublishQuestionRequest) (*PublishQuestionResponse, error)
	// 回答
	AnswerQuestion(context.Context, *AnswerQuestionRequest) (*AnswerQuestionResponse, error)
	// 采纳回答
	AcceptAnswer(context.Context, *AcceptAnswerRequest) (*AcceptAnswerResponse, error)
	// 问题列表
	Questions(context.Context, *QuestionsRequest) (*QuestionsResponse, error)
	// 问题详情
	QuestionDetail(context.Context, *QuestionDetailRequest) (*QuestionDetailResponse, error)
	// 删除问题
	QuestionDelete(context.Context, *QuestionDeleteRequest) (*QuestionDeleteResponse, error)
	// 回答列表
	AnswerList(context.Context, *AnswerListRequest) (*AnswerListResponse, error)
	// 删除回答
	AnswerDelete(context.Context, *AnswerDeleteRequest) (*AnswerDeleteResponse, error)
	// 搜索问题
	SearchQuestions(context.Context, *SearchQuestionsRequest) (*SearchQuestionsResponse, error)
	mustEmbedUnimplementedQAServer()
}

// UnimplementedQAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQAServer struct{}

func (UnimplementedQAServer) PublishQuestion(context.Context, *PublishQuestionRequest) (*PublishQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishQuestion not implemented")
}
func (UnimplementedQAServer) AnswerQuestion(context.Context, *AnswerQuestionRequest) (*AnswerQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerQuestion not implemented")
}
func (UnimplementedQAServer) AcceptAnswer(context.Context, *AcceptAnswerRequest) (*AcceptAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptAnswer not implemented")
}
func (UnimplementedQAServer) Questions(context.Context, *QuestionsRequest) (*QuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Questions not implemented")
}
func (UnimplementedQAServer) QuestionDetail(context.Context, *QuestionDetailRequest) (*QuestionDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestionDetail not implemented")
}
func (UnimplementedQAServer) QuestionDelete(context.Context, *QuestionDeleteRequest) (*QuestionDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestionDelete not implemented")
}
func (UnimplementedQAServer) AnswerList(context.Context, *AnswerListRequest) (*AnswerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerList not implemented")
}
func (UnimplementedQAServer) AnswerDelete(context.Context, *AnswerDeleteRequest) (*AnswerDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerDelete not implemented")
}
func (UnimplementedQAServer) SearchQuestions(context.Context, *SearchQuestionsRequest) (*SearchQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchQuestions not implemented")
}
func (UnimplementedQAServer) mustEmbedUnimplementedQAServer() {}
func (UnimplementedQAServer) testEmbeddedByValue()            {}

// UnsafeQAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QAServer will
// result in compilation errors.
type UnsafeQAServer interface {
	mustEmbedUnimplementedQAServer()
}

func RegisterQAServer(s grpc.ServiceRegistrar, srv QAServer) {
	// If the following call panics, it indicates UnimplementedQAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QA_ServiceDesc, srv)
}

func _QA_PublishQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).PublishQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_PublishQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).PublishQuestion(ctx, req.(*PublishQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AnswerQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AnswerQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AnswerQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AnswerQuestion(ctx, req.(*AnswerQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AcceptAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AcceptAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AcceptAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AcceptAnswer(ctx, req.(*AcceptAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_Questions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).Questions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_Questions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).Questions(ctx, req.(*QuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_QuestionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).QuestionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_QuestionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).QuestionDetail(ctx, req.(*QuestionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_QuestionDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).QuestionDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_QuestionDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).QuestionDelete(ctx, req.(*QuestionDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AnswerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AnswerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AnswerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AnswerList(ctx, req.(*AnswerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AnswerDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AnswerDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AnswerDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AnswerDelete(ctx, req.(*AnswerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_SearchQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).SearchQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_SearchQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).SearchQuestions(ctx, req.(*SearchQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QA_ServiceDesc is the grpc.ServiceDesc for QA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.QA",
	HandlerType: (*QAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishQuestion",
			Handler:    _QA_PublishQuestion_Handler,
		},
		{
			MethodName: "AnswerQuestion",
			Handler:    _QA_AnswerQuestion_Handler,
		},
		{
			MethodName: "AcceptAnswer",
			Handler:    _QA_AcceptAnswer_Handler,
		},
		{
			MethodName: "Questions",
			Handler:    _QA_Questions_Handler,
		},
		{
			MethodName: "QuestionDetail",
			Handler:    _QA_QuestionDetail_Handler,
		},
		{
			MethodName: "QuestionDelete",
			Handler:    _QA_QuestionDelete_Handler,
		},
		{
			MethodName: "AnswerList",
			Handler:    _QA_AnswerList_Handler,
		},
		{
			MethodName: "AnswerDelete",
			Handler:    _QA_AnswerDelete_Handler,
		},
		{
			MethodName: "SearchQuestions",
			Handler:    _QA_SearchQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qa.proto",
}
