// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: reply.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`                  // 业务ID
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"`           // 评论目标id
	ReplyUserId   int64                  `protobuf:"varint,3,opt,name=replyUserId,proto3" json:"replyUserId,omitempty"`     // 评论用户ID
	BeReplyUserId int64                  `protobuf:"varint,4,opt,name=beReplyUserId,proto3" json:"beReplyUserId,omitempty"` // 被回复用户ID
	ParentId      int64                  `protobuf:"varint,5,opt,name=parentId,proto3" json:"parentId,omitempty"`           // 父评论ID (0表示根评论)
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`              // 内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyRequest) Reset() {
	*x = CreateReplyRequest{}
	mi := &file_reply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyRequest) ProtoMessage() {}

func (x *CreateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReplyRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *CreateReplyRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CreateReplyRequest) GetReplyUserId() int64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *CreateReplyRequest) GetBeReplyUserId() int64 {
	if x != nil {
		return x.BeReplyUserId
	}
	return 0
}

func (x *CreateReplyRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"` // 评论ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyResponse) Reset() {
	*x = CreateReplyResponse{}
	mi := &file_reply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyResponse) ProtoMessage() {}

func (x *CreateReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyResponse.ProtoReflect.Descriptor instead.
func (*CreateReplyResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReplyResponse) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

type DeleteReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"` // 评论ID
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`   // 操作用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyRequest) Reset() {
	*x = DeleteReplyRequest{}
	mi := &file_reply_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyRequest) ProtoMessage() {}

func (x *DeleteReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteReplyRequest) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *DeleteReplyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyResponse) Reset() {
	*x = DeleteReplyResponse{}
	mi := &file_reply_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyResponse) ProtoMessage() {}

func (x *DeleteReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyResponse.ProtoReflect.Descriptor instead.
func (*DeleteReplyResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{3}
}

type ReplyDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"` // 评论ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyDetailRequest) Reset() {
	*x = ReplyDetailRequest{}
	mi := &file_reply_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyDetailRequest) ProtoMessage() {}

func (x *ReplyDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyDetailRequest.ProtoReflect.Descriptor instead.
func (*ReplyDetailRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{4}
}

func (x *ReplyDetailRequest) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

type ReplyDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *ReplyItem             `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"` // 评论详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyDetailResponse) Reset() {
	*x = ReplyDetailResponse{}
	mi := &file_reply_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyDetailResponse) ProtoMessage() {}

func (x *ReplyDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyDetailResponse.ProtoReflect.Descriptor instead.
func (*ReplyDetailResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyDetailResponse) GetReply() *ReplyItem {
	if x != nil {
		return x.Reply
	}
	return nil
}

type ReplyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`        // 业务ID
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"` // 评论目标id
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`     // 游标
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 页大小
	SortType      int32                  `protobuf:"varint,5,opt,name=sortType,proto3" json:"sortType,omitempty"` // 排序类型 0:按时间倒序 1:按点赞数倒序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyListRequest) Reset() {
	*x = ReplyListRequest{}
	mi := &file_reply_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyListRequest) ProtoMessage() {}

func (x *ReplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyListRequest.ProtoReflect.Descriptor instead.
func (*ReplyListRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyListRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ReplyListRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReplyListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ReplyListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReplyListRequest) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

type ReplyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`             // 评论ID
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`                  // 业务ID
	TargetId      int64                  `protobuf:"varint,3,opt,name=targetId,proto3" json:"targetId,omitempty"`           // 评论目标id
	ReplyUserId   int64                  `protobuf:"varint,4,opt,name=replyUserId,proto3" json:"replyUserId,omitempty"`     // 评论用户ID
	BeReplyUserId int64                  `protobuf:"varint,5,opt,name=beReplyUserId,proto3" json:"beReplyUserId,omitempty"` // 被回复用户ID
	ParentId      int64                  `protobuf:"varint,6,opt,name=parentId,proto3" json:"parentId,omitempty"`           // 父评论ID
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`              // 内容
	LikeNum       int64                  `protobuf:"varint,8,opt,name=likeNum,proto3" json:"likeNum,omitempty"`             // 点赞数
	CreateTime    int64                  `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`       // 创建时间
	SubReplies    []*ReplyItem           `protobuf:"bytes,10,rep,name=subReplies,proto3" json:"subReplies,omitempty"`       // 子回复列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyItem) Reset() {
	*x = ReplyItem{}
	mi := &file_reply_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyItem) ProtoMessage() {}

func (x *ReplyItem) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyItem.ProtoReflect.Descriptor instead.
func (*ReplyItem) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyItem) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *ReplyItem) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ReplyItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReplyItem) GetReplyUserId() int64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *ReplyItem) GetBeReplyUserId() int64 {
	if x != nil {
		return x.BeReplyUserId
	}
	return 0
}

func (x *ReplyItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ReplyItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyItem) GetLikeNum() int64 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *ReplyItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ReplyItem) GetSubReplies() []*ReplyItem {
	if x != nil {
		return x.SubReplies
	}
	return nil
}

type ReplyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ReplyItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`    // 评论列表
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // 下一页游标
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`   // 是否最后一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyListResponse) Reset() {
	*x = ReplyListResponse{}
	mi := &file_reply_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyListResponse) ProtoMessage() {}

func (x *ReplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyListResponse.ProtoReflect.Descriptor instead.
func (*ReplyListResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyListResponse) GetItems() []*ReplyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReplyListResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ReplyListResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type ReplyCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`        // 业务ID
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"` // 评论目标id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCountRequest) Reset() {
	*x = ReplyCountRequest{}
	mi := &file_reply_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCountRequest) ProtoMessage() {}

func (x *ReplyCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCountRequest.ProtoReflect.Descriptor instead.
func (*ReplyCountRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{9}
}

func (x *ReplyCountRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ReplyCountRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type ReplyCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyNum      int64                  `protobuf:"varint,1,opt,name=replyNum,proto3" json:"replyNum,omitempty"`         // 评论总数
	ReplyRootNum  int64                  `protobuf:"varint,2,opt,name=replyRootNum,proto3" json:"replyRootNum,omitempty"` // 根评论总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCountResponse) Reset() {
	*x = ReplyCountResponse{}
	mi := &file_reply_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCountResponse) ProtoMessage() {}

func (x *ReplyCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCountResponse.ProtoReflect.Descriptor instead.
func (*ReplyCountResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{10}
}

func (x *ReplyCountResponse) GetReplyNum() int64 {
	if x != nil {
		return x.ReplyNum
	}
	return 0
}

func (x *ReplyCountResponse) GetReplyRootNum() int64 {
	if x != nil {
		return x.ReplyRootNum
	}
	return 0
}

var File_reply_proto protoreflect.FileDescriptor

const file_reply_proto_rawDesc = "" +
	"\n" +
	"\vreply.proto\x12\aservice\"\xc4\x01\n" +
	"\x12CreateReplyRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\x12 \n" +
	"\vreplyUserId\x18\x03 \x01(\x03R\vreplyUserId\x12$\n" +
	"\rbeReplyUserId\x18\x04 \x01(\x03R\rbeReplyUserId\x12\x1a\n" +
	"\bparentId\x18\x05 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"/\n" +
	"\x13CreateReplyResponse\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\"F\n" +
	"\x12DeleteReplyRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"\x15\n" +
	"\x13DeleteReplyResponse\".\n" +
	"\x12ReplyDetailRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\"?\n" +
	"\x13ReplyDetailResponse\x12(\n" +
	"\x05reply\x18\x01 \x01(\v2\x12.service.ReplyItemR\x05reply\"\x94\x01\n" +
	"\x10ReplyListRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bsortType\x18\x05 \x01(\x05R\bsortType\"\xc3\x02\n" +
	"\tReplyItem\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\x03R\btargetId\x12 \n" +
	"\vreplyUserId\x18\x04 \x01(\x03R\vreplyUserId\x12$\n" +
	"\rbeReplyUserId\x18\x05 \x01(\x03R\rbeReplyUserId\x12\x1a\n" +
	"\bparentId\x18\x06 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x18\n" +
	"\alikeNum\x18\b \x01(\x03R\alikeNum\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\x03R\n" +
	"createTime\x122\n" +
	"\n" +
	"subReplies\x18\n" +
	" \x03(\v2\x12.service.ReplyItemR\n" +
	"subReplies\"k\n" +
	"\x11ReplyListResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.service.ReplyItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"E\n" +
	"\x11ReplyCountRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\"T\n" +
	"\x12ReplyCountResponse\x12\x1a\n" +
	"\breplyNum\x18\x01 \x01(\x03R\breplyNum\x12\"\n" +
	"\freplyRootNum\x18\x02 \x01(\x03R\freplyRootNum2\xf0\x02\n" +
	"\x05Reply\x12H\n" +
	"\vCreateReply\x12\x1b.service.CreateReplyRequest\x1a\x1c.service.CreateReplyResponse\x12H\n" +
	"\vDeleteReply\x12\x1b.service.DeleteReplyRequest\x1a\x1c.service.DeleteReplyResponse\x12H\n" +
	"\vReplyDetail\x12\x1b.service.ReplyDetailRequest\x1a\x1c.service.ReplyDetailResponse\x12B\n" +
	"\tReplyList\x12\x19.service.ReplyListRequest\x1a\x1a.service.ReplyListResponse\x12E\n" +
	"\n" +
	"ReplyCount\x12\x1a.service.ReplyCountRequest\x1a\x1b.service.ReplyCountResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_reply_proto_rawDescOnce sync.Once
	file_reply_proto_rawDescData []byte
)

func file_reply_proto_rawDescGZIP() []byte {
	file_reply_proto_rawDescOnce.Do(func() {
		file_reply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reply_proto_rawDesc), len(file_reply_proto_rawDesc)))
	})
	return file_reply_proto_rawDescData
}

var file_reply_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_reply_proto_goTypes = []any{
	(*CreateReplyRequest)(nil),  // 0: service.CreateReplyRequest
	(*CreateReplyResponse)(nil), // 1: service.CreateReplyResponse
	(*DeleteReplyRequest)(nil),  // 2: service.DeleteReplyRequest
	(*DeleteReplyResponse)(nil), // 3: service.DeleteReplyResponse
	(*ReplyDetailRequest)(nil),  // 4: service.ReplyDetailRequest
	(*ReplyDetailResponse)(nil), // 5: service.ReplyDetailResponse
	(*ReplyListRequest)(nil),    // 6: service.ReplyListRequest
	(*ReplyItem)(nil),           // 7: service.ReplyItem
	(*ReplyListResponse)(nil),   // 8: service.ReplyListResponse
	(*ReplyCountRequest)(nil),   // 9: service.ReplyCountRequest
	(*ReplyCountResponse)(nil),  // 10: service.ReplyCountResponse
}
var file_reply_proto_depIdxs = []int32{
	7,  // 0: service.ReplyDetailResponse.reply:type_name -> service.ReplyItem
	7,  // 1: service.ReplyItem.subReplies:type_name -> service.ReplyItem
	7,  // 2: service.ReplyListResponse.items:type_name -> service.ReplyItem
	0,  // 3: service.Reply.CreateReply:input_type -> service.CreateReplyRequest
	2,  // 4: service.Reply.DeleteReply:input_type -> service.DeleteReplyRequest
	4,  // 5: service.Reply.ReplyDetail:input_type -> service.ReplyDetailRequest
	6,  // 6: service.Reply.ReplyList:input_type -> service.ReplyListRequest
	9,  // 7: service.Reply.ReplyCount:input_type -> service.ReplyCountRequest
	1,  // 8: service.Reply.CreateReply:output_type -> service.CreateReplyResponse
	3,  // 9: service.Reply.DeleteReply:output_type -> service.DeleteReplyResponse
	5,  // 10: service.Reply.ReplyDetail:output_type -> service.ReplyDetailResponse
	8,  // 11: service.Reply.ReplyList:output_type -> service.ReplyListResponse
	10, // 12: service.Reply.ReplyCount:output_type -> service.ReplyCountResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_reply_proto_init() }
func file_reply_proto_init() {
	if File_reply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reply_proto_rawDesc), len(file_reply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reply_proto_goTypes,
		DependencyIndexes: file_reply_proto_depIdxs,
		MessageInfos:      file_reply_proto_msgTypes,
	}.Build()
	File_reply_proto = out.File
	file_reply_proto_goTypes = nil
	file_reply_proto_depIdxs = nil
}
