// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: member.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Member_MemberInfo_FullMethodName       = "/pb.Member/MemberInfo"
	Member_UpgradeMember_FullMethodName    = "/pb.Member/UpgradeMember"
	Member_CheckMemberRight_FullMethodName = "/pb.Member/CheckMemberRight"
	Member_MemberOrderList_FullMethodName  = "/pb.Member/MemberOrderList"
)

// MemberClient is the client API for Member service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemberClient interface {
	MemberInfo(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error)
	UpgradeMember(ctx context.Context, in *UpgradeMemberRequest, opts ...grpc.CallOption) (*UpgradeMemberResponse, error)
	CheckMemberRight(ctx context.Context, in *CheckMemberRightRequest, opts ...grpc.CallOption) (*CheckMemberRightResponse, error)
	MemberOrderList(ctx context.Context, in *MemberOrderListRequest, opts ...grpc.CallOption) (*MemberOrderListResponse, error)
}

type memberClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberClient(cc grpc.ClientConnInterface) MemberClient {
	return &memberClient{cc}
}

func (c *memberClient) MemberInfo(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberInfoResponse)
	err := c.cc.Invoke(ctx, Member_MemberInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) UpgradeMember(ctx context.Context, in *UpgradeMemberRequest, opts ...grpc.CallOption) (*UpgradeMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeMemberResponse)
	err := c.cc.Invoke(ctx, Member_UpgradeMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) CheckMemberRight(ctx context.Context, in *CheckMemberRightRequest, opts ...grpc.CallOption) (*CheckMemberRightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMemberRightResponse)
	err := c.cc.Invoke(ctx, Member_CheckMemberRight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) MemberOrderList(ctx context.Context, in *MemberOrderListRequest, opts ...grpc.CallOption) (*MemberOrderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberOrderListResponse)
	err := c.cc.Invoke(ctx, Member_MemberOrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServer is the server API for Member service.
// All implementations must embed UnimplementedMemberServer
// for forward compatibility.
type MemberServer interface {
	MemberInfo(context.Context, *MemberInfoRequest) (*MemberInfoResponse, error)
	UpgradeMember(context.Context, *UpgradeMemberRequest) (*UpgradeMemberResponse, error)
	CheckMemberRight(context.Context, *CheckMemberRightRequest) (*CheckMemberRightResponse, error)
	MemberOrderList(context.Context, *MemberOrderListRequest) (*MemberOrderListResponse, error)
	mustEmbedUnimplementedMemberServer()
}

// UnimplementedMemberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberServer struct{}

func (UnimplementedMemberServer) MemberInfo(context.Context, *MemberInfoRequest) (*MemberInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemberInfo not implemented")
}
func (UnimplementedMemberServer) UpgradeMember(context.Context, *UpgradeMemberRequest) (*UpgradeMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeMember not implemented")
}
func (UnimplementedMemberServer) CheckMemberRight(context.Context, *CheckMemberRightRequest) (*CheckMemberRightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMemberRight not implemented")
}
func (UnimplementedMemberServer) MemberOrderList(context.Context, *MemberOrderListRequest) (*MemberOrderListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemberOrderList not implemented")
}
func (UnimplementedMemberServer) mustEmbedUnimplementedMemberServer() {}
func (UnimplementedMemberServer) testEmbeddedByValue()                {}

// UnsafeMemberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberServer will
// result in compilation errors.
type UnsafeMemberServer interface {
	mustEmbedUnimplementedMemberServer()
}

func RegisterMemberServer(s grpc.ServiceRegistrar, srv MemberServer) {
	// If the following call panics, it indicates UnimplementedMemberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Member_ServiceDesc, srv)
}

func _Member_MemberInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).MemberInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_MemberInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).MemberInfo(ctx, req.(*MemberInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_UpgradeMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).UpgradeMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_UpgradeMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).UpgradeMember(ctx, req.(*UpgradeMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_CheckMemberRight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMemberRightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).CheckMemberRight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_CheckMemberRight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).CheckMemberRight(ctx, req.(*CheckMemberRightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_MemberOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberOrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).MemberOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_MemberOrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).MemberOrderList(ctx, req.(*MemberOrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Member_ServiceDesc is the grpc.ServiceDesc for Member service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Member_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Member",
	HandlerType: (*MemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MemberInfo",
			Handler:    _Member_MemberInfo_Handler,
		},
		{
			MethodName: "UpgradeMember",
			Handler:    _Member_UpgradeMember_Handler,
		},
		{
			MethodName: "CheckMemberRight",
			Handler:    _Member_CheckMemberRight_Handler,
		},
		{
			MethodName: "MemberOrderList",
			Handler:    _Member_MemberOrderList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member.proto",
}
