// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: concerned.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddConcernedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`    // 业务ID
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`   // 收藏对象id
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConcernedRequest) Reset() {
	*x = AddConcernedRequest{}
	mi := &file_concerned_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConcernedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConcernedRequest) ProtoMessage() {}

func (x *AddConcernedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConcernedRequest.ProtoReflect.Descriptor instead.
func (*AddConcernedRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{0}
}

func (x *AddConcernedRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *AddConcernedRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *AddConcernedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddConcernedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConcernedResponse) Reset() {
	*x = AddConcernedResponse{}
	mi := &file_concerned_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConcernedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConcernedResponse) ProtoMessage() {}

func (x *AddConcernedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConcernedResponse.ProtoReflect.Descriptor instead.
func (*AddConcernedResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{1}
}

type CancelConcernedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`    // 业务ID
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`   // 收藏对象id
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelConcernedRequest) Reset() {
	*x = CancelConcernedRequest{}
	mi := &file_concerned_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConcernedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConcernedRequest) ProtoMessage() {}

func (x *CancelConcernedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConcernedRequest.ProtoReflect.Descriptor instead.
func (*CancelConcernedRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{2}
}

func (x *CancelConcernedRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *CancelConcernedRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *CancelConcernedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelConcernedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelConcernedResponse) Reset() {
	*x = CancelConcernedResponse{}
	mi := &file_concerned_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConcernedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConcernedResponse) ProtoMessage() {}

func (x *CancelConcernedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConcernedResponse.ProtoReflect.Descriptor instead.
func (*CancelConcernedResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{3}
}

type IsConcernedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`    // 业务ID
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`   // 收藏对象id
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConcernedRequest) Reset() {
	*x = IsConcernedRequest{}
	mi := &file_concerned_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConcernedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConcernedRequest) ProtoMessage() {}

func (x *IsConcernedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConcernedRequest.ProtoReflect.Descriptor instead.
func (*IsConcernedRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{4}
}

func (x *IsConcernedRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *IsConcernedRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *IsConcernedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsConcernedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsConcerned   bool                   `protobuf:"varint,1,opt,name=isConcerned,proto3" json:"isConcerned,omitempty"` // 是否已收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConcernedResponse) Reset() {
	*x = IsConcernedResponse{}
	mi := &file_concerned_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConcernedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConcernedResponse) ProtoMessage() {}

func (x *IsConcernedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConcernedResponse.ProtoReflect.Descriptor instead.
func (*IsConcernedResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{5}
}

func (x *IsConcernedResponse) GetIsConcerned() bool {
	if x != nil {
		return x.IsConcerned
	}
	return false
}

type ConcernedListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`     // 用户ID
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`        // 业务ID (空表示全部)
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`     // 游标
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedListRequest) Reset() {
	*x = ConcernedListRequest{}
	mi := &file_concerned_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedListRequest) ProtoMessage() {}

func (x *ConcernedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedListRequest.ProtoReflect.Descriptor instead.
func (*ConcernedListRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{6}
}

func (x *ConcernedListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConcernedListRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ConcernedListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ConcernedListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ConcernedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                 // 记录ID
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`            // 业务ID
	ObjId         int64                  `protobuf:"varint,3,opt,name=objId,proto3" json:"objId,omitempty"`           // 收藏对象id
	CreateTime    int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"` // 收藏时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedItem) Reset() {
	*x = ConcernedItem{}
	mi := &file_concerned_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedItem) ProtoMessage() {}

func (x *ConcernedItem) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedItem.ProtoReflect.Descriptor instead.
func (*ConcernedItem) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{7}
}

func (x *ConcernedItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConcernedItem) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ConcernedItem) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *ConcernedItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ConcernedListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConcernedItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`    // 收藏列表
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // 下一页游标
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`   // 是否最后一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedListResponse) Reset() {
	*x = ConcernedListResponse{}
	mi := &file_concerned_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedListResponse) ProtoMessage() {}

func (x *ConcernedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedListResponse.ProtoReflect.Descriptor instead.
func (*ConcernedListResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{8}
}

func (x *ConcernedListResponse) GetItems() []*ConcernedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ConcernedListResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ConcernedListResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type ConcernedCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`  // 业务ID
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"` // 收藏对象id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedCountRequest) Reset() {
	*x = ConcernedCountRequest{}
	mi := &file_concerned_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedCountRequest) ProtoMessage() {}

func (x *ConcernedCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedCountRequest.ProtoReflect.Descriptor instead.
func (*ConcernedCountRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{9}
}

func (x *ConcernedCountRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ConcernedCountRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

type ConcernedCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConcernedNum  int64                  `protobuf:"varint,1,opt,name=concernedNum,proto3" json:"concernedNum,omitempty"` // 收藏数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedCountResponse) Reset() {
	*x = ConcernedCountResponse{}
	mi := &file_concerned_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedCountResponse) ProtoMessage() {}

func (x *ConcernedCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedCountResponse.ProtoReflect.Descriptor instead.
func (*ConcernedCountResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{10}
}

func (x *ConcernedCountResponse) GetConcernedNum() int64 {
	if x != nil {
		return x.ConcernedNum
	}
	return 0
}

var File_concerned_proto protoreflect.FileDescriptor

const file_concerned_proto_rawDesc = "" +
	"\n" +
	"\x0fconcerned.proto\x12\aservice\"Y\n" +
	"\x13AddConcernedRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"\x16\n" +
	"\x14AddConcernedResponse\"\\\n" +
	"\x16CancelConcernedRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"\x19\n" +
	"\x17CancelConcernedResponse\"X\n" +
	"\x12IsConcernedRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"7\n" +
	"\x13IsConcernedResponse\x12 \n" +
	"\visConcerned\x18\x01 \x01(\bR\visConcerned\"x\n" +
	"\x14ConcernedListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"k\n" +
	"\rConcernedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x03 \x01(\x03R\x05objId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\"s\n" +
	"\x15ConcernedListResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.service.ConcernedItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"C\n" +
	"\x15ConcernedCountRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\"<\n" +
	"\x16ConcernedCountResponse\x12\"\n" +
	"\fconcernedNum\x18\x01 \x01(\x03R\fconcernedNum2\x9b\x03\n" +
	"\tConcerned\x12K\n" +
	"\fAddConcerned\x12\x1c.service.AddConcernedRequest\x1a\x1d.service.AddConcernedResponse\x12T\n" +
	"\x0fCancelConcerned\x12\x1f.service.CancelConcernedRequest\x1a .service.CancelConcernedResponse\x12H\n" +
	"\vIsConcerned\x12\x1b.service.IsConcernedRequest\x1a\x1c.service.IsConcernedResponse\x12N\n" +
	"\rConcernedList\x12\x1d.service.ConcernedListRequest\x1a\x1e.service.ConcernedListResponse\x12Q\n" +
	"\x0eConcernedCount\x12\x1e.service.ConcernedCountRequest\x1a\x1f.service.ConcernedCountResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_concerned_proto_rawDescOnce sync.Once
	file_concerned_proto_rawDescData []byte
)

func file_concerned_proto_rawDescGZIP() []byte {
	file_concerned_proto_rawDescOnce.Do(func() {
		file_concerned_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_concerned_proto_rawDesc), len(file_concerned_proto_rawDesc)))
	})
	return file_concerned_proto_rawDescData
}

var file_concerned_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_concerned_proto_goTypes = []any{
	(*AddConcernedRequest)(nil),     // 0: service.AddConcernedRequest
	(*AddConcernedResponse)(nil),    // 1: service.AddConcernedResponse
	(*CancelConcernedRequest)(nil),  // 2: service.CancelConcernedRequest
	(*CancelConcernedResponse)(nil), // 3: service.CancelConcernedResponse
	(*IsConcernedRequest)(nil),      // 4: service.IsConcernedRequest
	(*IsConcernedResponse)(nil),     // 5: service.IsConcernedResponse
	(*ConcernedListRequest)(nil),    // 6: service.ConcernedListRequest
	(*ConcernedItem)(nil),           // 7: service.ConcernedItem
	(*ConcernedListResponse)(nil),   // 8: service.ConcernedListResponse
	(*ConcernedCountRequest)(nil),   // 9: service.ConcernedCountRequest
	(*ConcernedCountResponse)(nil),  // 10: service.ConcernedCountResponse
}
var file_concerned_proto_depIdxs = []int32{
	7,  // 0: service.ConcernedListResponse.items:type_name -> service.ConcernedItem
	0,  // 1: service.Concerned.AddConcerned:input_type -> service.AddConcernedRequest
	2,  // 2: service.Concerned.CancelConcerned:input_type -> service.CancelConcernedRequest
	4,  // 3: service.Concerned.IsConcerned:input_type -> service.IsConcernedRequest
	6,  // 4: service.Concerned.ConcernedList:input_type -> service.ConcernedListRequest
	9,  // 5: service.Concerned.ConcernedCount:input_type -> service.ConcernedCountRequest
	1,  // 6: service.Concerned.AddConcerned:output_type -> service.AddConcernedResponse
	3,  // 7: service.Concerned.CancelConcerned:output_type -> service.CancelConcernedResponse
	5,  // 8: service.Concerned.IsConcerned:output_type -> service.IsConcernedResponse
	8,  // 9: service.Concerned.ConcernedList:output_type -> service.ConcernedListResponse
	10, // 10: service.Concerned.ConcernedCount:output_type -> service.ConcernedCountResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_concerned_proto_init() }
func file_concerned_proto_init() {
	if File_concerned_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_concerned_proto_rawDesc), len(file_concerned_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_concerned_proto_goTypes,
		DependencyIndexes: file_concerned_proto_depIdxs,
		MessageInfos:      file_concerned_proto_msgTypes,
	}.Build()
	File_concerned_proto = out.File
	file_concerned_proto_goTypes = nil
	file_concerned_proto_depIdxs = nil
}
