// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: concerned.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Concerned_AddConcerned_FullMethodName    = "/service.Concerned/AddConcerned"
	Concerned_CancelConcerned_FullMethodName = "/service.Concerned/CancelConcerned"
	Concerned_IsConcerned_FullMethodName     = "/service.Concerned/IsConcerned"
	Concerned_ConcernedList_FullMethodName   = "/service.Concerned/ConcernedList"
	Concerned_ConcernedCount_FullMethodName  = "/service.Concerned/ConcernedCount"
)

// ConcernedClient is the client API for Concerned service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConcernedClient interface {
	// 收藏
	AddConcerned(ctx context.Context, in *AddConcernedRequest, opts ...grpc.CallOption) (*AddConcernedResponse, error)
	// 取消收藏
	CancelConcerned(ctx context.Context, in *CancelConcernedRequest, opts ...grpc.CallOption) (*CancelConcernedResponse, error)
	// 是否已收藏
	IsConcerned(ctx context.Context, in *IsConcernedRequest, opts ...grpc.CallOption) (*IsConcernedResponse, error)
	// 收藏列表
	ConcernedList(ctx context.Context, in *ConcernedListRequest, opts ...grpc.CallOption) (*ConcernedListResponse, error)
	// 收藏计数
	ConcernedCount(ctx context.Context, in *ConcernedCountRequest, opts ...grpc.CallOption) (*ConcernedCountResponse, error)
}

type concernedClient struct {
	cc grpc.ClientConnInterface
}

func NewConcernedClient(cc grpc.ClientConnInterface) ConcernedClient {
	return &concernedClient{cc}
}

func (c *concernedClient) AddConcerned(ctx context.Context, in *AddConcernedRequest, opts ...grpc.CallOption) (*AddConcernedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddConcernedResponse)
	err := c.cc.Invoke(ctx, Concerned_AddConcerned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) CancelConcerned(ctx context.Context, in *CancelConcernedRequest, opts ...grpc.CallOption) (*CancelConcernedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelConcernedResponse)
	err := c.cc.Invoke(ctx, Concerned_CancelConcerned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) IsConcerned(ctx context.Context, in *IsConcernedRequest, opts ...grpc.CallOption) (*IsConcernedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsConcernedResponse)
	err := c.cc.Invoke(ctx, Concerned_IsConcerned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) ConcernedList(ctx context.Context, in *ConcernedListRequest, opts ...grpc.CallOption) (*ConcernedListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConcernedListResponse)
	err := c.cc.Invoke(ctx, Concerned_ConcernedList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) ConcernedCount(ctx context.Context, in *ConcernedCountRequest, opts ...grpc.CallOption) (*ConcernedCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConcernedCountResponse)
	err := c.cc.Invoke(ctx, Concerned_ConcernedCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConcernedServer is the server API for Concerned service.
// All implementations must embed UnimplementedConcernedServer
// for forward compatibility.
type ConcernedServer interface {
	// 收藏
	AddConcerned(context.Context, *AddConcernedRequest) (*AddConcernedResponse, error)
	// 取消收藏
	CancelConcerned(context.Context, *CancelConcernedRequest) (*CancelConcernedResponse, error)
	// 是否已收藏
	IsConcerned(context.Context, *IsConcernedRequest) (*IsConcernedResponse, error)
	// 收藏列表
	ConcernedList(context.Context, *ConcernedListRequest) (*ConcernedListResponse, error)
	// 收藏计数
	ConcernedCount(context.Context, *ConcernedCountRequest) (*ConcernedCountResponse, error)
	mustEmbedUnimplementedConcernedServer()
}

// UnimplementedConcernedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConcernedServer struct{}

func (UnimplementedConcernedServer) AddConcerned(context.Context, *AddConcernedRequest) (*AddConcernedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddConcerned not implemented")
}
func (UnimplementedConcernedServer) CancelConcerned(context.Context, *CancelConcernedRequest) (*CancelConcernedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelConcerned not implemented")
}
func (UnimplementedConcernedServer) IsConcerned(context.Context, *IsConcernedRequest) (*IsConcernedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsConcerned not implemented")
}
func (UnimplementedConcernedServer) ConcernedList(context.Context, *ConcernedListRequest) (*ConcernedListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConcernedList not implemented")
}
func (UnimplementedConcernedServer) ConcernedCount(context.Context, *ConcernedCountRequest) (*ConcernedCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConcernedCount not implemented")
}
func (UnimplementedConcernedServer) mustEmbedUnimplementedConcernedServer() {}
func (UnimplementedConcernedServer) testEmbeddedByValue()                   {}

// UnsafeConcernedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConcernedServer will
// result in compilation errors.
type UnsafeConcernedServer interface {
	mustEmbedUnimplementedConcernedServer()
}

func RegisterConcernedServer(s grpc.ServiceRegistrar, srv ConcernedServer) {
	// If the following call panics, it indicates UnimplementedConcernedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Concerned_ServiceDesc, srv)
}

func _Concerned_AddConcerned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddConcernedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).AddConcerned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_AddConcerned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).AddConcerned(ctx, req.(*AddConcernedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_CancelConcerned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelConcernedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).CancelConcerned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_CancelConcerned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).CancelConcerned(ctx, req.(*CancelConcernedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_IsConcerned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsConcernedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).IsConcerned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_IsConcerned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).IsConcerned(ctx, req.(*IsConcernedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_ConcernedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcernedListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).ConcernedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_ConcernedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).ConcernedList(ctx, req.(*ConcernedListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_ConcernedCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcernedCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).ConcernedCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_ConcernedCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).ConcernedCount(ctx, req.(*ConcernedCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Concerned_ServiceDesc is the grpc.ServiceDesc for Concerned service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Concerned_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Concerned",
	HandlerType: (*ConcernedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddConcerned",
			Handler:    _Concerned_AddConcerned_Handler,
		},
		{
			MethodName: "CancelConcerned",
			Handler:    _Concerned_CancelConcerned_Handler,
		},
		{
			MethodName: "IsConcerned",
			Handler:    _Concerned_IsConcerned_Handler,
		},
		{
			MethodName: "ConcernedList",
			Handler:    _Concerned_ConcernedList_Handler,
		},
		{
			MethodName: "ConcernedCount",
			Handler:    _Concerned_ConcernedCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "concerned.proto",
}
