// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginRequest struct {
	Mobile           string `json:"mobile"`
	VerificationCode string `json:"verification_code"`
}

type LoginResponse struct {
	UserId int64 `json:"userId"`
	Token  Token `json:"token"`
}

type RegisterRequest struct {
	Name             string `json:"name"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}

type ThumbupRequest struct {
	BizId    string `json:"biz_id"`
	ObjId    int64  `json:"obj_id"`
	LikeType int32  `json:"like_type"`
}

type ThumbupResponse struct {
	BizId     string `json:"biz_id"`
	ObjId     int64  `json:"obj_id"`
	LikeNum   int64  `json:"like_num"`
	DislikeNum int64 `json:"dislike_num"`
}

type IsThumbupRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
}

type IsThumbupResponse struct {
	LikeType    int32 `json:"like_type"`
	ThumbupTime int64 `json:"thumbup_time"`
}

type FollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type FollowResponse struct{}

type UnfollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type UnfollowResponse struct{}

type FollowListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FollowItem struct {
	Id             int64 `json:"id"`
	FollowedUserId int64 `json:"followed_user_id"`
	CreateTime     int64 `json:"create_time"`
	FansCount      int64 `json:"fans_count"`
}

type FollowListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type FansListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FansListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type NotificationRequest struct {
	NotifType int32 `form:"notif_type"`
	Cursor    int64 `form:"cursor"`
	PageSize  int64 `form:"page_size"`
}

type NotificationItem struct {
	Id            int64  `json:"id"`
	Type          int32  `json:"type"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	IsRead        bool   `json:"is_read"`
	TriggerUserId int64  `json:"trigger_user_id"`
	RefId         int64  `json:"ref_id"`
	CreateTime    int64  `json:"create_time"`
}

type NotificationResponse struct {
	Items  []*NotificationItem `json:"items"`
	Cursor int64               `json:"cursor"`
	IsEnd  bool                `json:"is_end"`
}

type UnreadCountResponse struct {
	Total      int64           `json:"total"`
	TypeCounts map[int32]int64 `json:"type_counts"`
}

type MarkReadRequest struct {
	NotificationId int64 `json:"notification_id"`
}

type MarkReadResponse struct{}

type MarkAllReadRequest struct {
	NotifType int32 `json:"notif_type"`
}

type ConcernedAddRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedAddResponse struct{}

type ConcernedCancelRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedCancelResponse struct{}

type ConcernedCheckRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ConcernedCheckResponse struct {
	IsConcerned bool `json:"is_concerned"`
}

type ConcernedListRequest struct {
	BizId    string `form:"biz_id"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type ConcernedItem struct {
	Id         int64  `json:"id"`
	BizId      string `json:"biz_id"`
	ObjId      int64  `json:"obj_id"`
	CreateTime int64  `json:"create_time"`
}

type ConcernedListResponse struct {
	Items  []*ConcernedItem `json:"items"`
	Cursor int64            `json:"cursor"`
	IsEnd  bool             `json:"is_end"`
}

type MemberInfoResponse struct {
	UserId     int64  `json:"user_id"`
	Level      int32  `json:"level"`
	LevelName  string `json:"level_name"`
	ExpireTime int64  `json:"expire_time"`
	Status     int32  `json:"status"`
}

type MemberRightRequest struct {
	RightKey string `form:"right_key"`
}

type MemberRightResponse struct {
	HasRight bool  `json:"has_right"`
	Level    int32 `json:"level"`
}
