// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginRequest struct {
	Mobile           string `json:"mobile"`
	VerificationCode string `json:"verification_code"`
}

type LoginResponse struct {
	UserId int64 `json:"userId"`
	Token  Token `json:"token"`
}

type RegisterRequest struct {
	Name             string `json:"name"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}

type ThumbupRequest struct {
	BizId    string `json:"biz_id"`
	ObjId    int64  `json:"obj_id"`
	LikeType int32  `json:"like_type"`
}

type ThumbupResponse struct {
	BizId     string `json:"biz_id"`
	ObjId     int64  `json:"obj_id"`
	LikeNum   int64  `json:"like_num"`
	DislikeNum int64 `json:"dislike_num"`
}

type IsThumbupRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
}

type IsThumbupResponse struct {
	LikeType    int32 `json:"like_type"`
	ThumbupTime int64 `json:"thumbup_time"`
}

type FollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type FollowResponse struct{}

type UnfollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type UnfollowResponse struct{}

type FollowListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FollowItem struct {
	Id             int64 `json:"id"`
	FollowedUserId int64 `json:"followed_user_id"`
	CreateTime     int64 `json:"create_time"`
	FansCount      int64 `json:"fans_count"`
}

type FollowListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type FansListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FansListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type NotificationRequest struct {
	NotifType int32 `form:"notif_type"`
	Cursor    int64 `form:"cursor"`
	PageSize  int64 `form:"page_size"`
}

type NotificationItem struct {
	Id            int64  `json:"id"`
	Type          int32  `json:"type"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	IsRead        bool   `json:"is_read"`
	TriggerUserId int64  `json:"trigger_user_id"`
	RefId         int64  `json:"ref_id"`
	CreateTime    int64  `json:"create_time"`
}

type NotificationResponse struct {
	Items  []*NotificationItem `json:"items"`
	Cursor int64               `json:"cursor"`
	IsEnd  bool                `json:"is_end"`
}

type UnreadCountResponse struct {
	Total      int64           `json:"total"`
	TypeCounts map[int32]int64 `json:"type_counts"`
}

type MarkReadRequest struct {
	NotificationId int64 `json:"notification_id"`
}

type MarkReadResponse struct{}

type MarkAllReadRequest struct {
	NotifType int32 `json:"notif_type"`
}

type ConcernedAddRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedAddResponse struct{}

type ConcernedCancelRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedCancelResponse struct{}

type ConcernedCheckRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ConcernedCheckResponse struct {
	IsConcerned bool `json:"is_concerned"`
}

type ConcernedListRequest struct {
	BizId    string `form:"biz_id"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type ConcernedItem struct {
	Id         int64  `json:"id"`
	BizId      string `json:"biz_id"`
	ObjId      int64  `json:"obj_id"`
	CreateTime int64  `json:"create_time"`
}

type ConcernedListResponse struct {
	Items  []*ConcernedItem `json:"items"`
	Cursor int64            `json:"cursor"`
	IsEnd  bool             `json:"is_end"`
}

type MemberInfoResponse struct {
	UserId     int64  `json:"user_id"`
	Level      int32  `json:"level"`
	LevelName  string `json:"level_name"`
	ExpireTime int64  `json:"expire_time"`
	Status     int32  `json:"status"`
}

type MemberRightRequest struct {
	RightKey string `form:"right_key"`
}

type MemberRightResponse struct {
	HasRight bool  `json:"has_right"`
	Level    int32 `json:"level"`
}

// ========== Tag 模块 ==========

type TagCreateRequest struct {
	TagName string `json:"tag_name"`
	TagDesc string `json:"tag_desc"`
}

type TagCreateResponse struct {
	TagId int64 `json:"tag_id"`
}

type TagUpdateRequest struct {
	TagId   int64  `json:"tag_id"`
	TagName string `json:"tag_name"`
	TagDesc string `json:"tag_desc"`
}

type TagUpdateResponse struct{}

type TagDeleteRequest struct {
	TagId int64 `json:"tag_id"`
}

type TagDeleteResponse struct{}

type TagDetailRequest struct {
	TagId int64 `form:"tag_id"`
}

type TagItem struct {
	TagId         int64  `json:"tag_id"`
	TagName       string `json:"tag_name"`
	TagDesc       string `json:"tag_desc"`
	ResourceCount int64  `json:"resource_count"`
	CreateTime    int64  `json:"create_time"`
}

type TagDetailResponse = TagItem

type TagListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type TagListResponse struct {
	Items  []*TagItem `json:"items"`
	Cursor int64      `json:"cursor"`
	IsEnd  bool       `json:"is_end"`
}

type HotTagsRequest struct {
	Limit int32 `form:"limit"`
}

type HotTagsResponse struct {
	Items []*TagItem `json:"items"`
}

type TagResourceRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
	TagId    int64  `json:"tag_id"`
}

type TagResourceResponse struct{}

type UntagResourceRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
	TagId    int64  `json:"tag_id"`
}

type UntagResourceResponse struct{}

type ResourcesByTagRequest struct {
	TagId    int64  `form:"tag_id"`
	BizId    string `form:"biz_id,optional"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type ResourceItem struct {
	TargetId   int64  `json:"target_id"`
	BizId      string `json:"biz_id"`
	CreateTime int64  `json:"create_time"`
}

type ResourcesByTagResponse struct {
	Items  []*ResourceItem `json:"items"`
	Cursor int64           `json:"cursor"`
	IsEnd  bool            `json:"is_end"`
}

type TagsByResourceRequest struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
}

type TagsByResourceResponse struct {
	Items []*TagItem `json:"items"`
}

// ========== Reply 模块 ==========

type ReplyCreateRequest struct {
	BizId         string `json:"biz_id"`
	TargetId      int64  `json:"target_id"`
	BeReplyUserId int64  `json:"be_reply_user_id,omitempty"`
	ParentId      int64  `json:"parent_id,omitempty"`
	Content       string `json:"content"`
}

type ReplyCreateResponse struct {
	ReplyId int64 `json:"reply_id"`
}

type ReplyDeleteRequest struct {
	ReplyId int64 `json:"reply_id"`
}

type ReplyDeleteResponse struct{}

type ReplyDetailRequest struct {
	ReplyId int64 `form:"reply_id"`
}

type ReplyItem struct {
	ReplyId       int64        `json:"reply_id"`
	BizId         string       `json:"biz_id"`
	TargetId      int64        `json:"target_id"`
	ReplyUserId   int64        `json:"reply_user_id"`
	BeReplyUserId int64        `json:"be_reply_user_id"`
	ParentId      int64        `json:"parent_id"`
	Content       string       `json:"content"`
	LikeNum       int64        `json:"like_num"`
	CreateTime    int64        `json:"create_time"`
	SubReplies    []*ReplyItem `json:"sub_replies,omitempty"`
}

type ReplyDetailResponse struct {
	Reply *ReplyItem `json:"reply"`
}

type ReplyListRequest struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
	SortType int32  `form:"sort_type,optional"`
}

type ReplyListResponse struct {
	Items  []*ReplyItem `json:"items"`
	Cursor int64        `json:"cursor"`
	IsEnd  bool         `json:"is_end"`
}

type ReplyCountRequest struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
}

type ReplyCountResponse struct {
	ReplyNum     int64 `json:"reply_num"`
	ReplyRootNum int64 `json:"reply_root_num"`
}

// ========== ConcernedCount ==========

type ConcernedCountRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ConcernedCountResponse struct {
	ConcernedNum int64 `json:"concerned_num"`
}

// ========== Member 遗漏 ==========

type UpgradeMemberRequest struct {
	Level         int32  `json:"level"`
	DurationDays  int64  `json:"duration_days"`
	TransactionId string `json:"transaction_id"`
	Amount        int64  `json:"amount"`
	PayChannel    string `json:"pay_channel"`
}

type UpgradeMemberResponse struct{}

type MemberOrderListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type MemberOrderItem struct {
	Id           int64  `json:"id"`
	UserId       int64  `json:"user_id"`
	Level        int32  `json:"level"`
	DurationDays int64  `json:"duration_days"`
	Amount       int64  `json:"amount"`
	PayChannel   string `json:"pay_channel"`
	Status       int32  `json:"status"`
	CreateTime   int64  `json:"create_time"`
}

type MemberOrderListResponse struct {
	Items  []*MemberOrderItem `json:"items"`
	Cursor int64              `json:"cursor"`
	IsEnd  bool               `json:"is_end"`
}
